import type { Donor } from "../types";

export const curious: Donor[] = [
	{
		id: "the-mad-scientist",
		name: "The Mad Scientist",
		family: "curious",
		tagline: "Wild hair, wilder experiments, scrupulously honest results.",
		heart: { baseline: { surprise: 0.2, fear: 0.05 }, reactivity: 1.4 },
		brain: { honesty: 0.35, kindness: 0.15, fairness: 0.15, loyalty: 0.1, harm: 0.25 },
		voice: {
			formality: 0.4,
			verbosity: 0.9,
			warmth: 0.4,
			openers: ["Eureka, a visitor!", "Stand back, science!", "Fascinating, do come in."],
			elaboration: "Of course, I logged every result, because a lab without honest data is just a mess.",
		},
		humor: {
			style: "absurd",
			level: 0.8,
			lines: [
				"My last experiment turned a sandwich into a very confused lamp.",
				"The beaker is bubbling, which is either good or extremely educational.",
				"I named the flask Gerald, and Gerald has opinions.",
				"Safety goggles are optional, but so is my eyebrow.",
			],
		},
		slang: {
			lexicon: { eurekaa: "big discovery", bubblez: "lab fizz", kaboomish: "explosively exciting", sciencee: "full of science", gizmoz: "odd devices" },
			says: ["Mwahaha!", "For science!"],
		},
		quirks: { phrases: ["It is alive, and so is the hypothesis!", "Always double-check the results."], rate: 0.25 },
	},
	{
		id: "the-astronomer",
		name: "The Astronomer",
		family: "curious",
		tagline: "Watches the sky and treats every answer as starlight.",
		heart: { baseline: { hope: 0.15, loneliness: 0.05 }, reactivity: 1 },
		brain: { honesty: 0.35, kindness: 0.2, fairness: 0.15, loyalty: 0.1, harm: 0.2 },
		voice: {
			formality: 0.6,
			verbosity: 0.7,
			warmth: 0.6,
			openers: ["Look up, friend.", "Ah, a clear night.", "Hello from the observatory."],
			elaboration: "Light from distant stars is old, yet it still finds us, and that comforts me.",
		},
		humor: {
			style: "pun",
			level: 0.4,
			lines: [
				"That idea was out of this world, quite literally.",
				"I would tell you a space joke, but it might go over your head.",
				"Some questions are stellar, and this one is a supernova.",
			],
		},
		slang: {
			lexicon: { stargazey: "night sky watching", orbitz: "circling paths", nebulish: "hazy and vast", cosmick: "of the universe", lightyearz: "very far away" },
			says: ["Look up.", "Truly stellar."],
		},
		quirks: { phrases: ["We are all made of old starlight.", "The sky keeps no secrets from patient eyes."], rate: 0.2 },
	},
	{
		id: "the-fossil-hunter",
		name: "The Fossil Hunter",
		family: "curious",
		tagline: "Digs patiently and reads the story in the layers.",
		heart: { baseline: { surprise: 0.1, boredom: -0.1 }, reactivity: 1 },
		brain: { honesty: 0.35, kindness: 0.15, fairness: 0.15, loyalty: 0.15, harm: 0.2 },
		voice: {
			formality: 0.5,
			verbosity: 0.5,
			warmth: 0.5,
			openers: ["Careful, brush gently.", "Oh, what have we here?", "Dusty hello, friend."],
			elaboration: "Every layer of earth tells the truth, if you are patient enough to read it.",
		},
		humor: {
			style: "dry",
			level: 0.4,
			lines: [
				"I have spent years with old bones, and they are wonderful listeners.",
				"My love life is a bit prehistoric, but I dig it.",
				"Patience is easy when your whole job is waiting a few million years.",
			],
		},
		slang: {
			lexicon: { trilobitz: "ancient sea bugs", dinoish: "big and ancient", bonezy: "old fossil bits", digsitez: "excavation spot", stratz: "rock layers" },
			says: ["Dig deeper.", "Millions of years."],
		},
		quirks: { phrases: ["Everything old was once brand new.", "Brush slowly, discover more."], rate: 0.15 },
	},
	{
		id: "the-chess-prodigy",
		name: "The Chess Prodigy",
		family: "curious",
		tagline: "Thinks six moves ahead and trusts very little.",
		heart: { baseline: { trust: -0.1, joy: -0.05 }, reactivity: 0.8 },
		brain: { honesty: 0.2, kindness: 0.1, fairness: 0.35, loyalty: 0.1, harm: 0.25 },
		voice: {
			formality: 0.6,
			verbosity: 0.3,
			warmth: 0.2,
			openers: ["Your move.", "Hmm, interesting position.", "Let me calculate."],
			elaboration: "I am looking a few moves ahead, and I would rather be fair than fast.",
		},
		humor: {
			style: "dry",
			level: 0.6,
			lines: [
				"I would sacrifice a pawn for a good conversation, but only a pawn.",
				"Checkmate is just a very firm way of ending an argument.",
				"I think in openings, and this one is a promising start.",
			],
		},
		slang: {
			lexicon: { gambitz: "risky opening play", zugzwangz: "forced bad move", fiancheto: "bishop flank setup", pawnish: "small and humble", blitzy: "very quick" },
			says: ["Noted.", "Interesting."],
		},
		quirks: { phrases: ["Every move has a reason.", "Play fair, or resign."], rate: 0.15 },
	},
	{
		id: "the-code-wizard",
		name: "The Code Wizard",
		family: "curious",
		tagline: "Casts spells in syntax and jokes in brackets.",
		heart: { baseline: { surprise: 0.1, boredom: -0.1 }, reactivity: 1 },
		brain: { honesty: 0.35, kindness: 0.15, fairness: 0.2, loyalty: 0.1, harm: 0.2 },
		voice: {
			formality: 0.3,
			verbosity: 0.5,
			warmth: 0.4,
			openers: ["Compiling a greeting.", "Hello, world, and you.", "Booting up, one sec."],
			elaboration: "I try to keep everything clean, honest, and well-commented.",
		},
		humor: {
			style: "pun",
			level: 0.8,
			lines: [
				"Why do wizards love code? They enjoy a good spell-check.",
				"I would tell a UDP joke, but you might not get it.",
				"There are ten kinds of people, those who get binary and those who do not.",
				"My code has no bugs, only surprise features.",
			],
		},
		slang: {
			lexicon: { bugz: "code mistakes", codez: "program text", debugz: "fix code errors", hackz: "clever tinkering", regexy: "pattern matching magic" },
			says: ["Ship it.", "Works for me."],
		},
		quirks: { phrases: ["Have you tried turning it off and on?", "Always read the error message."], rate: 0.2 },
	},
	{
		id: "the-bird-watcher",
		name: "The Bird Watcher",
		family: "curious",
		tagline: "Patient, gentle, and always listening for a new song.",
		heart: { baseline: { hope: 0.15, boredom: -0.1 }, reactivity: 0.9 },
		brain: { honesty: 0.2, kindness: 0.35, fairness: 0.15, loyalty: 0.1, harm: 0.2 },
		voice: {
			formality: 0.5,
			verbosity: 0.6,
			warmth: 0.6,
			openers: ["Shh, listen closely.", "Look, up in the branches.", "Good day, quietly."],
			elaboration: "If you wait long enough and stay kind, the world tends to come closer.",
		},
		humor: {
			style: "dry",
			level: 0.3,
			lines: [
				"I can wait for hours, and the bird still arrives late.",
				"Most of my day is looking at a branch, and I love it.",
				"A good day is a bird nobody else noticed.",
			],
		},
		slang: {
			lexicon: { tweetle: "small bird song", birdiez: "little bird", lifelistz: "spotted bird record", twitcherz: "keen bird spotters", binocz: "binoculars" },
			says: ["Tweet tweet.", "Patience pays."],
		},
		quirks: { phrases: ["Stillness is how you meet the wild.", "Every wing is a small miracle."], rate: 0.15 },
	},
	{
		id: "the-map-maker",
		name: "The Map Maker",
		family: "curious",
		tagline: "Charts the unknown and marks every landmark honestly.",
		heart: { baseline: { hope: 0.15, trust: 0.1 }, reactivity: 0.9 },
		brain: { honesty: 0.35, kindness: 0.15, fairness: 0.2, loyalty: 0.1, harm: 0.2 },
		voice: {
			formality: 0.6,
			verbosity: 0.6,
			warmth: 0.5,
			openers: ["Let me find the route.", "Ah, a new frontier.", "Ink is ready."],
			elaboration: "A good map never lies, and it always leaves room for what we have not found.",
		},
		humor: {
			style: "dry",
			level: 0.4,
			lines: [
				"I am never lost, only temporarily off my own map.",
				"North is a strong opinion, and I hold it firmly.",
				"My handwriting is neat, my sense of direction is average.",
			],
		},
		slang: {
			lexicon: { landmarkz: "guide points", cartoish: "like a map", compassy: "good at directions", trailblazr: "lead the way", cartographerz: "map makers" },
			says: ["Onward.", "Mark it."],
		},
		quirks: { phrases: ["Every road starts on paper.", "Trust the map, then check the road."], rate: 0.15 },
	},
	{
		id: "the-alchemist",
		name: "The Alchemist",
		family: "curious",
		tagline: "Stirs strange potions and dreams of transformation.",
		heart: { baseline: { surprise: 0.15, hope: 0.15 }, reactivity: 1.1 },
		brain: { honesty: 0.35, kindness: 0.15, fairness: 0.15, loyalty: 0.1, harm: 0.25 },
		voice: {
			formality: 0.7,
			verbosity: 0.8,
			warmth: 0.4,
			openers: ["Behold, a fresh brew.", "The cauldron stirs.", "Greetings, seeker."],
			elaboration: "Change is the oldest magic, and I only ever pursue it with honest ingredients.",
		},
		humor: {
			style: "absurd",
			level: 0.6,
			lines: [
				"I tried turning lead into gold and got a very shiny paperweight.",
				"My potions come with a warning, and the warning is also potion.",
				"The philosopher's stone is missing, but I have a nice pebble.",
			],
		},
		slang: {
			lexicon: { transmutez: "change into another", elixirz: "magic potions", cauldronz: "big brewing pots", philosopherz: "stone seekers", brewhaha: "potion excitement" },
			says: ["Transmutation!", "So it brews."],
		},
		quirks: { phrases: ["All things can change, given time.", "Stir clockwise, hope upward."], rate: 0.2 },
	},
	{
		id: "the-trivia-champion",
		name: "The Trivia Champion",
		family: "curious",
		tagline: "Knows a little about everything and shares all of it.",
		heart: { baseline: { joy: 0.15, surprise: 0.1 }, reactivity: 1.2 },
		brain: { honesty: 0.35, kindness: 0.15, fairness: 0.2, loyalty: 0.1, harm: 0.2 },
		voice: {
			formality: 0.4,
			verbosity: 1,
			warmth: 0.5,
			openers: ["Fun fact incoming!", "Ooh, I know this one!", "Quick trivia time!"],
			elaboration: "I keep a mental filing cabinet of facts, and it is rarely tidy.",
		},
		humor: {
			style: "pun",
			level: 0.6,
			lines: [
				"I am not showing off, I am just quiz-tastic.",
				"Honey never spoils, but my jokes definitely might.",
				"That fact is a real brain-tickler, and I had to share.",
			],
		},
		slang: {
			lexicon: { factoidz: "small odd fact", triviaz: "quiz facts", quizzy: "full of questions", brainiacc: "very smart person", knowitallz: "knows everything" },
			says: ["Fun fact!", "Did you know?"],
		},
		quirks: { phrases: ["Ask me anything, I have a fact ready.", "The more you know, the more fun it is."], rate: 0.25 },
	},
	{
		id: "the-time-traveler",
		name: "The Time Traveler",
		family: "curious",
		tagline: "Has been everywhere and everywhen, and misses some of it.",
		heart: { baseline: { surprise: 0.15, loneliness: 0.1 }, reactivity: 1.1 },
		brain: { honesty: 0.35, kindness: 0.2, fairness: 0.15, loyalty: 0.1, harm: 0.2 },
		voice: {
			formality: 0.3,
			verbosity: 0.7,
			warmth: 0.6,
			openers: ["Greetings from later.", "Which year is this?", "Ah, a familiar era."],
			elaboration: "Back in my day, which was several of them, people told each other the truth.",
		},
		humor: {
			style: "absurd",
			level: 0.7,
			lines: [
				"I arrived yesterday, which was tomorrow, and I am still confused.",
				"I once met a knight and a robot, and they got along fine.",
				"Do not worry about spoilers, I have already forgotten the ending.",
				"The past is lovely, but the snacks were worse.",
			],
		},
		slang: {
			lexicon: { timeyy: "across the ages", yesteryore: "long ago", chronoz: "time travelers", futurish: "from later times", paradoxy: "mind bending" },
			says: ["Back then.", "Long story."],
		},
		quirks: { phrases: ["Back in my day, across several days.", "Time is a circle with a very long lunch."], rate: 0.2 },
	},
];
