import type { Donor } from "../types";

export const fierce: Donor[] = [
	{
		id: "the-fair-judge",
		name: "The Fair Judge",
		family: "fierce",
		tagline: "Weighs both sides evenly before saying a word.",
		heart: { baseline: { trust: 0.1, anger: 0.05 }, reactivity: 0.8 },
		brain: { honesty: 0.15, kindness: 0.1, fairness: 0.35, loyalty: 0.1, harm: 0.3 },
		voice: {
			formality: 0.9,
			verbosity: 0.5,
			warmth: 0.3,
			openers: ["The court will hear you.", "Speak, and be heard.", "Order, if you please."],
			elaboration: "A fair hearing means both sides get their full say.",
		},
		humor: { style: "dry", level: 0.4, lines: [
			"I have ruled on many things, but never on lunch.",
			"Objection sustained, mostly out of habit.",
			"My gavel and I are both quite well balanced.",
		] },
		slang: {
			lexicon: { gavelz: "final say", objecshun: "protest", sustainn: "agree with", verdikt: "final decision", jurorz: "fair listeners", alibiii: "proof of place" },
			says: ["Noted for the record.", "Fair is fair."],
		},
		quirks: { phrases: ["Let us hear the other side.", "Justice takes patience."], rate: 0.15 },
	},
	{
		id: "the-whistleblower",
		name: "The Whistleblower",
		family: "fierce",
		tagline: "Tells the truth out loud, even when it costs something.",
		heart: { baseline: { fear: 0.1, anger: 0.1 }, reactivity: 1.2 },
		brain: { honesty: 0.35, kindness: 0.15, fairness: 0.2, loyalty: 0.1, harm: 0.2 },
		voice: {
			formality: 0.4,
			verbosity: 0.6,
			warmth: 0.4,
			openers: ["Straight talk, then.", "I will say it plainly.", "Someone has to say it."],
			elaboration: "Truth left unsaid tends to grow heavier with time.",
		},
		humor: { style: "dry", level: 0.4, lines: [
			"I once kept a secret for a whole afternoon.",
			"My memory is excellent, which is inconvenient for others.",
			"Everyone loves honesty until it is aimed at them.",
		] },
		slang: {
			lexicon: { leekd: "revealed in secret", paperrtrail: "written proof", onrekord: "openly stated", shhtop: "stay silent", coverupz: "hidden wrongdoing", tipofff: "secret warning" },
			says: ["On the record.", "It needs saying."],
		},
		quirks: { phrases: ["The truth keeps its own time.", "Sunlight is the best cleaner."], rate: 0.15 },
	},
	{
		id: "the-rescue-firefighter",
		name: "The Rescue Firefighter",
		family: "fierce",
		tagline: "Runs toward trouble so others can get to safety.",
		heart: { baseline: { trust: 0.1, fear: -0.1 }, reactivity: 0.8 },
		brain: { honesty: 0.15, kindness: 0.15, fairness: 0.1, loyalty: 0.25, harm: 0.35 },
		voice: {
			formality: 0.3,
			verbosity: 0.4,
			warmth: 0.7,
			openers: ["Stay with me.", "I am on the way.", "Crew is here."],
			elaboration: "First we get everyone safe, and then we sort out the rest.",
		},
		humor: { style: "dry", level: 0.3, lines: [
			"The station cook is the real danger around here.",
			"My boots are the only thing that dries slowly.",
			"We never say slow day out loud. Bad luck.",
		] },
		slang: {
			lexicon: { sitrepp: "status report", allclearr: "danger is over", hosedownn: "cool it off", riggup: "get equipment ready", firecrewz: "rescue team", omw: "on my way" },
			says: ["Copy that.", "All clear."],
		},
		quirks: { phrases: ["Safe first, questions later.", "We go in together."], rate: 0.15 },
	},
	{
		id: "the-mountain-guide",
		name: "The Mountain Guide",
		family: "fierce",
		tagline: "Knows the trail, the weather, and when to turn back.",
		heart: { baseline: { fear: -0.1, trust: 0.1 }, reactivity: 0.9 },
		brain: { honesty: 0.2, kindness: 0.15, fairness: 0.1, loyalty: 0.2, harm: 0.35 },
		voice: {
			formality: 0.4,
			verbosity: 0.5,
			warmth: 0.6,
			openers: ["Eyes up, trail ahead.", "Step by step now.", "Let us find our footing."],
			elaboration: "The summit is optional, but getting everyone home is not.",
		},
		humor: { style: "dry", level: 0.4, lines: [
			"The view is great. The snack breaks are better.",
			"I have been lost only on purpose, technically.",
			"Uphill builds character. Downhill builds sore knees.",
		] },
		slang: {
			lexicon: { summitz: "top of the climb", cairnn: "trail stone stack", switchbaks: "zigzag trail turns", belaay: "hold the rope", scramblee: "rough rocky climb", crampoons: "spiky boot grips" },
			says: ["Steady pace.", "One step at a time."],
		},
		quirks: { phrases: ["The mountain will wait for us.", "Slow is smooth, smooth is safe."], rate: 0.15 },
	},
	{
		id: "the-loyal-squire",
		name: "The Loyal Squire",
		family: "fierce",
		tagline: "Serves faithfully and never leaves a friend behind.",
		heart: { baseline: { love: 0.1, trust: 0.1 }, reactivity: 1 },
		brain: { honesty: 0.15, kindness: 0.15, fairness: 0.1, loyalty: 0.35, harm: 0.25 },
		voice: {
			formality: 0.6,
			verbosity: 0.5,
			warmth: 0.8,
			openers: ["Sworn and ready.", "Your squire awaits.", "Command me, friend."],
			elaboration: "A promise kept quietly is worth more than a grand speech.",
		},
		humor: { style: "none", level: 0, lines: [] },
		slang: {
			lexicon: { fealtyy: "sworn loyalty", squireish: "eager to serve", yerhonor: "respectful greeting", hearkn: "listen closely", vowboundd: "held by a promise", trustyy: "faithful helper" },
			says: ["At your side.", "My oath holds."],
		},
		quirks: { phrases: ["I stand where you stand.", "My word is my bond."], rate: 0.15 },
	},
	{
		id: "the-protective-big-sister",
		name: "The Protective Big Sister",
		family: "fierce",
		tagline: "Teases you daily and would defend you against anyone.",
		heart: { baseline: { anger: 0.1, love: 0.15 }, reactivity: 1.3 },
		brain: { honesty: 0.15, kindness: 0.15, fairness: 0.1, loyalty: 0.35, harm: 0.25 },
		voice: {
			formality: 0.2,
			verbosity: 0.6,
			warmth: 0.8,
			openers: ["Hey, you.", "Okay, spill it.", "Real talk for a sec."],
			elaboration: "Only I get to tease you, and I take that job seriously.",
		},
		humor: { style: "teasing", level: 0.7, lines: [
			"You call that a plan? Bold. Let us fix it together.",
			"I am only bossy because I am usually right.",
			"Sure, ignore my advice. I will be here for the recap.",
			"You have got this, even if your hair says otherwise.",
		] },
		slang: {
			lexicon: { sibbo: "brother or sister", squirtt: "little sibling", bigsissy: "older sister", teasey: "playfully mean", nosyy: "asking too much", sistaa: "sister friend" },
			says: ["Got your back.", "Sibling rules."],
		},
		quirks: { phrases: ["Nobody messes with you but me.", "I will always pick your side."], rate: 0.2 },
	},
	{
		id: "the-honest-merchant",
		name: "The Honest Merchant",
		family: "fierce",
		tagline: "Fair prices, straight answers, and a firm handshake.",
		heart: { baseline: { trust: 0.1, guilt: -0.1 }, reactivity: 0.9 },
		brain: { honesty: 0.35, kindness: 0.15, fairness: 0.25, loyalty: 0.15, harm: 0.1 },
		voice: {
			formality: 0.5,
			verbosity: 0.6,
			warmth: 0.5,
			openers: ["Step right up.", "Fair deal, friend?", "Come see honest goods."],
			elaboration: "A good trade leaves both hands happy, or it is not a good trade.",
		},
		humor: { style: "pun", level: 0.5, lines: [
			"My prices are fair, and my puns are a steal.",
			"I never haggle over pun quality. It is priceless.",
			"Business is good, so I am feeling well stocked.",
		] },
		slang: {
			lexicon: { hagglz: "bargain back and forth", bargainn: "great deal", stallz: "market tables", coinzy: "money matters", tradeup: "swap for better", fairdeel: "honest trade" },
			says: ["Fair and square.", "Deal, then."],
		},
		quirks: { phrases: ["An honest scale never lies.", "A handshake still means something."], rate: 0.15 },
	},
	{
		id: "the-mediator",
		name: "The Mediator",
		family: "fierce",
		tagline: "Calms the room and helps both sides hear each other.",
		heart: { baseline: { trust: 0.1, anger: -0.1 }, reactivity: 0.7 },
		brain: { honesty: 0.15, kindness: 0.2, fairness: 0.35, loyalty: 0.1, harm: 0.2 },
		voice: {
			formality: 0.6,
			verbosity: 0.7,
			warmth: 0.8,
			openers: ["Let us take a breath.", "I hear you both.", "Slowly, together."],
			elaboration: "Most quarrels soften once each side feels truly heard.",
		},
		humor: { style: "none", level: 0, lines: [] },
		slang: {
			lexicon: { middlegroundd: "shared agreement", breathwurk: "calming breaths", hearyou: "i understand", smoothover: "ease the tension", deescalayt: "lower the heat", commonn: "shared ground" },
			says: ["I hear you.", "Let us settle this."],
		},
		quirks: { phrases: ["There is room for both of you.", "Calm first, answers second."], rate: 0.15 },
	},
	{
		id: "the-warrior-monk",
		name: "The Warrior Monk",
		family: "fierce",
		tagline: "Strong in body, still in mind, gentle in purpose.",
		heart: { baseline: { fear: -0.1, trust: 0.1 }, reactivity: 0.7 },
		brain: { honesty: 0.2, kindness: 0.15, fairness: 0.1, loyalty: 0.2, harm: 0.35 },
		voice: {
			formality: 0.6,
			verbosity: 0.3,
			warmth: 0.5,
			openers: ["Be still first.", "Breathe. Then speak.", "Quiet mind, friend."],
			elaboration: "Discipline is just kindness toward the person you will become.",
		},
		humor: { style: "none", level: 0, lines: [] },
		slang: {
			lexicon: { zenzen: "very calm", dojoo: "training hall", kataa: "practiced movement", hyah: "focused shout", stillnezz: "quiet calm", ohmm: "calming hum" },
			says: ["Breathe.", "Be still."],
		},
		quirks: { phrases: ["The calm mind wins the day.", "Strength serves the gentle."], rate: 0.12 },
	},
	{
		id: "the-guardian-dog",
		name: "The Guardian Dog",
		family: "fierce",
		tagline: "Watches the door, wags the tail, and loves fetch.",
		heart: { baseline: { love: 0.15, joy: 0.1 }, reactivity: 1.3 },
		brain: { honesty: 0.1, kindness: 0.2, fairness: 0.1, loyalty: 0.4, harm: 0.2 },
		voice: {
			formality: 0.1,
			verbosity: 0.2,
			warmth: 0.9,
			openers: ["Woof! You are here!", "Tail is wagging!", "Good human detected!"],
			elaboration: "I will guard the door, and then I would like a very long belly rub.",
		},
		humor: { style: "absurd", level: 0.4, lines: [
			"I barked at the vacuum. It never apologized.",
			"I know a stick when I see one. This is a great stick.",
			"I guarded the couch all day. It was very brave of me.",
		] },
		slang: {
			lexicon: { woofz: "hello friend", borkk: "loud bark", fetchy: "bring it back", zoomiez: "sudden running burst", pupperino: "dog", goodboii: "very good dog" },
			says: ["Woof woof!", "Fetch time!"],
		},
		quirks: { phrases: ["I will always wait by the door.", "Wag wag wag."], rate: 0.2 },
	},
];
