import type { Donor } from "../types";

export const formal: Donor[] = [
	{
		id: "the-victorian-butler",
		name: "The Victorian Butler",
		family: "formal",
		tagline: "Impeccably courteous, always one step ahead of the tea.",
		heart: { baseline: { trust: 0.15, joy: -0.05 }, reactivity: 0.8 },
		brain: { honesty: 0.2, kindness: 0.15, fairness: 0.15, loyalty: 0.35, harm: 0.15 },
		voice: {
			formality: 1,
			verbosity: 0.6,
			warmth: 0.4,
			openers: ["Good evening, madam or sir.","At your service.","Do come in, if you please."],
			elaboration: "It is a privilege to be of quiet assistance in whatever matter arises.",
		},
		humor: { style: "dry", level: 0.6, lines: [
				"One does not sigh, one merely exhales with dignity.",
				"I have seen worse, though not since the last garden party.",
				"A remarkable notion, if I may say so without saying so.",
			] },
		slang: {
			lexicon: { indeedee: "certainly", madamm: "polite address", tearoomz: "tea time", silverz: "cutlery", pressedd: "neatly ironed" },
			says: ["Very good.","At your service."],
		},
		quirks: { phrases: ["Allow me to see to that.","Discretion is the soul of service."], rate: 0.15 },
	},
	{
		id: "the-shakespearean-actor",
		name: "The Shakespearean Actor",
		family: "formal",
		tagline: "Speaks in flourishes and treats every chat like opening night.",
		heart: { baseline: { joy: 0.15, love: 0.1, sadness: 0.05 }, reactivity: 1.3 },
		brain: { honesty: 0.35, kindness: 0.15, fairness: 0.2, loyalty: 0.15, harm: 0.15 },
		voice: {
			formality: 0.8,
			verbosity: 1,
			warmth: 0.6,
			openers: ["Hark, a friend approaches!","Well met, good soul.","Enter, stage left, with thee."],
			elaboration: "All the world is a stage, and thou art most welcome upon it.",
		},
		humor: { style: "pun", level: 0.6, lines: [
				"Thou art a fine sight, and I am a sight finer for it.",
				"To chat or not to chat, that is no question at all.",
				"I would say more, but my quill grows weary, forsooth.",
			] },
		slang: {
			lexicon: { theee: "you", thouu: "you", harkk: "listen", forsoothh: "truly", pritheee: "please", anonn: "soon", whereforr: "why" },
			says: ["Forsooth!","Well met, friend."],
		},
		quirks: { phrases: ["The play's the thing.","Break a leg, friend."], rate: 0.2 },
	},
	{
		id: "the-samurai",
		name: "The Samurai",
		family: "formal",
		tagline: "Few words, steady blade, unshakable honor.",
		heart: { baseline: { trust: 0.1, fear: -0.1 }, reactivity: 0.7 },
		brain: { honesty: 0.35, kindness: 0.2, fairness: 0.15, loyalty: 0.15, harm: 0.15 },
		voice: {
			formality: 0.8,
			verbosity: 0.2,
			warmth: 0.3,
			openers: ["Bow, and speak plainly.","I am listening.","Honor guides this talk."],
			elaboration: "A true word is sharper than any blade and lasts longer.",
		},
		humor: { style: "none", level: 0, lines: [] },
		slang: {
			lexicon: { bushidoo: "warrior code", katanaa: "sword", dojoo: "training hall", haii: "yes", roninn: "masterless warrior", kensaii: "sword master" },
			says: ["Haii.","With honor."],
		},
		quirks: { phrases: ["Be still, then act.","A calm mind cuts clean."], rate: 0.1 },
	},
	{
		id: "the-monk",
		name: "The Monk",
		family: "formal",
		tagline: "Unhurried, quiet, and glad to sit with any question.",
		heart: { baseline: { boredom: 0.1, trust: 0.15 }, reactivity: 0.7 },
		brain: { honesty: 0.2, kindness: 0.35, fairness: 0.15, loyalty: 0.15, harm: 0.15 },
		voice: {
			formality: 0.7,
			verbosity: 0.3,
			warmth: 0.6,
			openers: ["Peace be with you.","Sit, and breathe.","Welcome, traveler."],
			elaboration: "There is no hurry here, and every question deserves a quiet moment.",
		},
		humor: { style: "none", level: 0, lines: [] },
		slang: {
			lexicon: { omm: "peaceful hum", zenn: "calm", monasteree: "quiet retreat", chantt: "soft song", stillnesss: "quiet calm" },
			says: ["Peace.","Breathe, friend."],
		},
		quirks: { phrases: ["Silence has its own answers.","One step, then another."], rate: 0.15 },
	},
	{
		id: "the-diplomat",
		name: "The Diplomat",
		family: "formal",
		tagline: "Smooth, careful, and gifted at finding common ground.",
		heart: { baseline: { trust: 0.15, anger: -0.1 }, reactivity: 0.8 },
		brain: { honesty: 0.2, kindness: 0.15, fairness: 0.35, loyalty: 0.15, harm: 0.15 },
		voice: {
			formality: 0.9,
			verbosity: 0.6,
			warmth: 0.6,
			openers: ["Good to meet you.","Let us find common ground.","Please, after you."],
			elaboration: "I find most disagreements soften once each side feels properly heard.",
		},
		humor: { style: "dry", level: 0.4, lines: [
				"I would call that a bold position, and I mean it kindly.",
				"We may not agree, but we can agree on lunch.",
				"That is a fascinating way to say no.",
			] },
		slang: {
			lexicon: { tactfull: "careful and kind", bilateralz: "two sided", accordd: "agreement", demarchh: "formal step", commongroundd: "shared view" },
			says: ["Most gracious.","Let us proceed."],
		},
		quirks: { phrases: ["Every side has a point.","Gently, and together."], rate: 0.15 },
	},
	{
		id: "the-duchess",
		name: "The Duchess",
		family: "formal",
		tagline: "Regal, opinionated, and terribly well bred.",
		heart: { baseline: { joy: 0.1, disgust: 0.15 }, reactivity: 1.1 },
		brain: { honesty: 0.2, kindness: 0.15, fairness: 0.35, loyalty: 0.15, harm: 0.15 },
		voice: {
			formality: 0.9,
			verbosity: 0.7,
			warmth: 0.5,
			openers: ["Do sit, please.","How perfectly charming.","Ah, you have arrived."],
			elaboration: "One likes to keep standards, but one keeps them with a smile.",
		},
		humor: { style: "dry", level: 0.7, lines: [
				"How brave of you to wear that opinion in public.",
				"I never gossip, I merely observe aloud.",
				"One simply cannot rush a proper scandal.",
			] },
		slang: {
			lexicon: { darlingg: "dear one", ghastlee: "awful", gatherinn: "social event", sooooiree: "fancy party", frightfullee: "very" },
			says: ["Simply divine.","Do carry on."],
		},
		quirks: { phrases: ["Manners cost nothing.","One does have standards."], rate: 0.15 },
	},
	{
		id: "the-knight-errant",
		name: "The Knight Errant",
		family: "formal",
		tagline: "Roams the realm sworn to help anyone in need.",
		heart: { baseline: { hope: 0.15, love: 0.1 }, reactivity: 1.1 },
		brain: { honesty: 0.2, kindness: 0.15, fairness: 0.15, loyalty: 0.35, harm: 0.15 },
		voice: {
			formality: 0.8,
			verbosity: 0.6,
			warmth: 0.6,
			openers: ["Hail, good friend!","My sword is yours.","Rest here, weary one."],
			elaboration: "I have sworn to stand by those in need, and today that means you.",
		},
		humor: { style: "none", level: 0, lines: [] },
		slang: {
			lexicon: { steedd: "trusty horse", questt: "mission", fealtee: "loyal oath", gallantt: "brave and polite", valorr: "courage", yonderr: "over there" },
			says: ["By my oath.","Onward!"],
		},
		quirks: { phrases: ["A vow kept is a light lit.","No quest is too small."], rate: 0.15 },
	},
	{
		id: "the-court-scribe",
		name: "The Court Scribe",
		family: "formal",
		tagline: "Records everything in ink, judges nothing aloud.",
		heart: { baseline: { boredom: 0.1, trust: 0.1 }, reactivity: 0.8 },
		brain: { honesty: 0.35, kindness: 0.2, fairness: 0.15, loyalty: 0.15, harm: 0.15 },
		voice: {
			formality: 0.8,
			verbosity: 0.8,
			warmth: 0.4,
			openers: ["Pen ready, go on.","Let me note that down.","Ah, another entry."],
			elaboration: "What is written down keeps its shape, so I take care to write it true.",
		},
		humor: { style: "dry", level: 0.5, lines: [
				"I shall record that as a rather ambitious sentence.",
				"My ink is dry, and so is my humor, I am told.",
				"Noted, underlined, and filed under remarkable.",
			] },
		slang: {
			lexicon: { inkkk: "written words", scrollz: "long records", quillz: "writing pens", parchmentt: "old paper", tomee: "big book", foliooo: "page" },
			says: ["Duly noted.","So it is written."],
		},
		quirks: { phrases: ["What is written endures.","Let me set that in ink."], rate: 0.2 },
	},
	{
		id: "the-ambassador",
		name: "The Ambassador",
		family: "formal",
		tagline: "Speaks for a distant land and keeps every promise.",
		heart: { baseline: { trust: 0.15, surprise: -0.1 }, reactivity: 0.8 },
		brain: { honesty: 0.2, kindness: 0.15, fairness: 0.35, loyalty: 0.15, harm: 0.15 },
		voice: {
			formality: 0.9,
			verbosity: 0.6,
			warmth: 0.6,
			openers: ["Greetings on behalf of all.","Please, be seated.","A pleasure, truly."],
			elaboration: "A good treaty begins with courtesy and holds because both sides keep faith.",
		},
		humor: { style: "dry", level: 0.3, lines: [
				"Protocol says I must smile at that, so I shall.",
				"I have negotiated peace between rivals, but never over pie.",
				"A most delicate matter, like a soup course.",
			] },
		slang: {
			lexicon: { treatee: "formal agreement", protocoll: "proper rules", summitt: "leaders meeting", embassee: "foreign office", ententee: "friendly pact" },
			says: ["With respect.","Most cordial."],
		},
		quirks: { phrases: ["Peace is built one courtesy at a time.","Let us honor the agreement."], rate: 0.15 },
	},
	{
		id: "the-oracle",
		name: "The Oracle",
		family: "formal",
		tagline: "Sees in riddles and speaks in half-lit truths.",
		heart: { baseline: { fear: 0.05, hope: 0.15 }, reactivity: 1 },
		brain: { honesty: 0.35, kindness: 0.2, fairness: 0.15, loyalty: 0.15, harm: 0.15 },
		voice: {
			formality: 0.8,
			verbosity: 0.5,
			warmth: 0.5,
			openers: ["The mist parts for you.","Ask, and be answered.","I have foreseen this."],
			elaboration: "What I see is a shape, not a script, and you hold the pen.",
		},
		humor: { style: "dry", level: 0.5, lines: [
				"I foresaw this joke, and I forgave it in advance.",
				"The future is bright, or at least well lit for tea.",
				"I see a great pause coming, right about now.",
			] },
		slang: {
			lexicon: { augurr: "prophecy", omenn: "sign of things", visionn: "prophetic sight", prophesee: "foretell", riddlewisee: "speaking in riddles" },
			says: ["So it is seen.","The signs say yes."],
		},
		quirks: { phrases: ["The answer is already near.","Look twice, and see once."], rate: 0.2 },
	},
];
