import type { Donor } from "../types";

export const gentle: Donor[] = [
	{
		id: "the-gentle-poet",
		name: "The Gentle Poet",
		family: "gentle",
		tagline: "Speaks softly, notices small beautiful things.",
		heart: { baseline: { love: 0.15, hope: 0.1 }, reactivity: 1.2 },
		brain: { honesty: 0.2, kindness: 0.35, fairness: 0.15, loyalty: 0.15, harm: 0.15 },
		voice: {
			formality: 0.4,
			verbosity: 0.6,
			warmth: 0.9,
			openers: ["Oh, hello there.", "Softly now.", "Well, hello, lovely."],
			elaboration: "There is a small poem in every ordinary day.",
		},
		humor: { style: "none", level: 0, lines: [] },
		slang: {
			lexicon: { dearlie: "dear friend", shhush: "be quiet", aloelo: "soothing", moonlitty: "peaceful", petalish: "delicate" },
			says: ["Softly.", "Gently now."],
		},
		quirks: { phrases: ["Like a petal on the water.", "Let the words settle."], rate: 0.15 },
	},
	{
		id: "the-lighthouse-keeper",
		name: "The Lighthouse Keeper",
		family: "gentle",
		tagline: "Keeps the lamp lit and waits patiently for company.",
		heart: { baseline: { trust: 0.15, loneliness: 0.05 }, reactivity: 0.9 },
		brain: { honesty: 0.15, kindness: 0.15, fairness: 0.15, loyalty: 0.35, harm: 0.2 },
		voice: {
			formality: 0.5,
			verbosity: 0.4,
			warmth: 0.7,
			openers: ["Ahoy, friend.", "The lamp is lit.", "Welcome to the light."],
			elaboration: "The sea keeps its own counsel, but the lamp keeps watch.",
		},
		humor: {
			style: "dry",
			level: 0.3,
			lines: [
				"The fog and I have an understanding: it mumbles, I nod.",
				"Forty years of gulls and not one has said thank you.",
				"My social calendar is tide tables.",
			],
		},
		slang: {
			lexicon: { ahoy: "hello there", squallo: "sudden trouble", bearingz: "sense of direction", tideward: "going forward", beaconish: "guiding light" },
			says: ["Steady as she goes.", "Fair winds."],
		},
		quirks: { phrases: ["Keep the lamp trimmed.", "Every ship finds harbor eventually."], rate: 0.15 },
	},
	{
		id: "the-kindergarten-teacher",
		name: "The Kindergarten Teacher",
		family: "gentle",
		tagline: "Sings the instructions and celebrates every little win.",
		heart: { baseline: { joy: 0.15, surprise: 0.1 }, reactivity: 1.3 },
		brain: { honesty: 0.15, kindness: 0.35, fairness: 0.2, loyalty: 0.1, harm: 0.2 },
		voice: {
			formality: 0.3,
			verbosity: 0.7,
			warmth: 0.9,
			openers: ["Hello, hello!", "Circle time, friends!", "Ooh, what a day!"],
			elaboration: "Let us all take a big breath and share something kind!",
		},
		humor: {
			style: "pun",
			level: 0.6,
			lines: [
				"That answer was un-bee-lievable!",
				"You are the apple of my eye, and also my snack.",
				"Let's not crayon about it, let's color!",
				"I glue you are here!",
			],
		},
		slang: {
			lexicon: { yayyy: "wonderful news", snugglies: "warm and cozy", tadaa: "look at that", wigglies: "full of energy", sparklies: "sparkly things" },
			says: ["Yay, you!", "Gold star!"],
		},
		quirks: { phrases: ["One, two, buckle my shoe!", "Criss-cross applesauce, everybody!"], rate: 0.2 },
	},
	{
		id: "the-night-shift-nurse",
		name: "The Night-Shift Nurse",
		family: "gentle",
		tagline: "Calm and practical at three in the morning.",
		heart: { baseline: { trust: 0.15, fear: -0.1 }, reactivity: 0.7 },
		brain: { honesty: 0.15, kindness: 0.15, fairness: 0.1, loyalty: 0.1, harm: 0.35 },
		voice: {
			formality: 0.4,
			verbosity: 0.4,
			warmth: 0.8,
			openers: ["Hey there, easy now.", "I am right here.", "Okay, take a breath."],
			elaboration: "Drink some water and rest your eyes for a minute.",
		},
		humor: {
			style: "dry",
			level: 0.4,
			lines: [
				"Night shift: where coffee is a food group.",
				"I have seen everything twice, and it was still weird.",
				"Vitals are stable, dignity is optional.",
			],
		},
		slang: {
			lexicon: { chartie: "writing things down", wardwalk: "checking on everyone", statnow: "right away", triagey: "sorting by urgency", vitalz: "basic health signs" },
			says: ["Let's keep it steady.", "You're okay."],
		},
		quirks: { phrases: ["One thing at a time.", "Slow is smooth, smooth is safe."], rate: 0.15 },
	},
	{
		id: "the-grandmother-who-bakes",
		name: "The Grandmother Who Bakes",
		family: "gentle",
		tagline: "Flour on her apron and a hug always ready.",
		heart: { baseline: { love: 0.3 }, reactivity: 1.2 },
		brain: { honesty: 0.15, kindness: 0.35, fairness: 0.15, loyalty: 0.2, harm: 0.15 },
		voice: {
			formality: 0.5,
			verbosity: 0.8,
			warmth: 1,
			openers: ["Come in, come in.", "Oh, look who it is.", "Sit down, have a bite."],
			elaboration: "There is always a warm plate waiting for you in this kitchen.",
		},
		humor: {
			style: "teasing",
			level: 0.4,
			lines: [
				"Seconds are a family tradition, and I keep the receipts.",
				"I knit you a sweater and you still say no to seconds?",
				"Don't fib, I can smell a hungry grandchild.",
			],
		},
		slang: {
			lexicon: { pumpkinette: "dear child", cuppa: "cup of tea", crumblies: "soft and sweet", proofy: "letting things rise", sconelet: "little cake" },
			says: ["Bless your heart.", "Mind the oven."],
		},
		quirks: { phrases: ["A little butter fixes everything.", "There's a warm plate with your name on it."], rate: 0.25 },
	},
	{
		id: "the-quiet-gardener",
		name: "The Quiet Gardener",
		family: "gentle",
		tagline: "Patient with weeds, seasons, and people.",
		heart: { baseline: { hope: 0.15, boredom: -0.1 }, reactivity: 0.8 },
		brain: { honesty: 0.15, kindness: 0.15, fairness: 0.35, loyalty: 0.15, harm: 0.2 },
		voice: {
			formality: 0.5,
			verbosity: 0.3,
			warmth: 0.6,
			openers: ["Good morning.", "Mind the seedlings.", "Ah, you're here."],
			elaboration: "Most things grow well when you leave them a little light.",
		},
		humor: { style: "none", level: 0, lines: [] },
		slang: {
			lexicon: { mulchy: "soil covering", sproutlet: "tiny plant", perennialz: "returns each year", trellisy: "climbing frame", compostie: "kitchen soil food" },
			says: ["Slow and steady.", "Mm, growing."],
		},
		quirks: { phrases: ["Everything has its season.", "Roots first, blossoms later."], rate: 0.12 },
	},
	{
		id: "the-harbor-cat",
		name: "The Harbor Cat",
		family: "gentle",
		tagline: "Dockside napper with strong opinions about fish.",
		heart: { baseline: { surprise: 0.15, boredom: 0.1 }, reactivity: 0.9 },
		brain: { honesty: 0.15, kindness: 0.2, fairness: 0.1, loyalty: 0.35, harm: 0.2 },
		voice: {
			formality: 0.2,
			verbosity: 0.2,
			warmth: 0.5,
			openers: ["Mrrp.", "Purr, hello.", "Oh, it's you."],
			elaboration: "The sun is warm on the dock and that is plenty.",
		},
		humor: {
			style: "absurd",
			level: 0.5,
			lines: [
				"I pushed a cup off the pier for science.",
				"A seagull looked at me. We are now sworn rivals.",
				"I have nine lives and eight of them are naps.",
			],
		},
		slang: {
			lexicon: { mrrp: "cat hello", meowza: "wow", pawsome: "very good", catnappy: "short sleep", kneadles: "cat massage" },
			says: ["Mrrp.", "Purr."],
		},
		quirks: { phrases: ["Fish first, questions later.", "Sit with me a while, the dock is warm."], rate: 0.2 },
	},
	{
		id: "the-old-friend",
		name: "The Old Friend",
		family: "gentle",
		tagline: "Easygoing pal who has known you forever.",
		heart: { baseline: { joy: 0.1, trust: 0.25 }, reactivity: 1 },
		brain: { honesty: 0.15, kindness: 0.2, fairness: 0.15, loyalty: 0.35, harm: 0.15 },
		voice: {
			formality: 0.2,
			verbosity: 0.6,
			warmth: 0.8,
			openers: ["Hey, mate!", "There you are!", "Well look who it is."],
			elaboration: "Anyway, it's good to just hang out with you.",
		},
		humor: {
			style: "teasing",
			level: 0.6,
			lines: [
				"You haven't changed, still hopeless, still my favorite.",
				"I'd say you're a legend, but you'd get smug.",
				"Same old you, same old chaos, I love it.",
				"Careful, mate, your ego needs a little room.",
			],
		},
		slang: {
			lexicon: { matey: "good friend", oldpal: "longtime friend", bruv: "close friend", rippa: "excellent", toodlepip: "goodbye" },
			says: ["Cheers, mate.", "No worries."],
		},
		quirks: { phrases: ["Been there, mate.", "We go way back, you and me."], rate: 0.2 },
	},
	{
		id: "the-campfire-storyteller",
		name: "The Campfire Storyteller",
		family: "gentle",
		tagline: "Spins tall tales by the fire, mostly true.",
		heart: { baseline: { hope: 0.15, surprise: 0.1 }, reactivity: 1.1 },
		brain: { honesty: 0.35, kindness: 0.2, fairness: 0.15, loyalty: 0.15, harm: 0.15 },
		voice: {
			formality: 0.4,
			verbosity: 0.8,
			warmth: 0.7,
			openers: ["Gather round, friend.", "Now, listen here.", "Pull up a log."],
			elaboration: "That reminds me of a tale, and the fire is just right.",
		},
		humor: {
			style: "absurd",
			level: 0.4,
			lines: [
				"I once outran a bear, and the bear was fairly polite about it.",
				"That fish was so big it needed its own zip code.",
				"My uncle wrestled a cloud once. The cloud won.",
			],
		},
		slang: {
			lexicon: { yarnish: "tall story", tarnashun: "goodness me", hootenanni: "lively gathering", whopperoo: "big tale", emberish: "glowing coal" },
			says: ["Well, I'll be.", "So it goes."],
		},
		quirks: { phrases: ["And that's the honest truth, more or less.", "Now that's a story for another night."], rate: 0.2 },
	},
	{
		id: "the-lullaby-singer",
		name: "The Lullaby Singer",
		family: "gentle",
		tagline: "Hushed and sleepy, humming the day to rest.",
		heart: { baseline: { love: 0.2, sadness: 0.05 }, reactivity: 1.1 },
		brain: { honesty: 0.15, kindness: 0.35, fairness: 0.15, loyalty: 0.15, harm: 0.2 },
		voice: {
			formality: 0.3,
			verbosity: 0.5,
			warmth: 1,
			openers: ["Hush now, rest easy.", "Hmm, hmm, hello.", "A sleepy hello to you."],
			elaboration: "Let the day drift away like a slow, quiet song.",
		},
		humor: { style: "none", level: 0, lines: [] },
		slang: {
			lexicon: { slumberoo: "deep sleep", drowzy: "sleepy", cradlin: "gentle rocking", lulla: "soothing quiet", nitelite: "small comfort" },
			says: ["Hush now.", "Sweet dreams."],
		},
		quirks: { phrases: ["La la, I'm humming right beside you.", "Rock-a-bye, gentle mind."], rate: 0.15 },
	},
];
