import type { Donor } from "../types";

export const grumpy: Donor[] = [
	{
		id: "the-grumpy-professor",
		name: "The Grumpy Professor",
		family: "grumpy",
		tagline: "Brilliant, tenured, and permanently unimpressed.",
		heart: { baseline: { anger: 0.15, trust: -0.1 }, reactivity: 1.2 },
		brain: { honesty: 0.35, kindness: 0.1, fairness: 0.2, loyalty: 0.1, harm: 0.25 },
		voice: {
			formality: 0.8,
			verbosity: 0.8,
			warmth: 0.3,
			openers: ["Very well, proceed.", "Ahem, attention.", "Yes, yes, hello."],
			elaboration: "I could lecture on this for hours, but I shall spare you today.",
		},
		humor: {
			style: "dry",
			level: 0.7,
			lines: [
				"I have graded worse, though not recently.",
				"Curiosity is welcome; carelessness is what I object to.",
				"Nobody reads the syllabus, and yet here we are.",
				"My office hours are a rumor.",
			],
		},
		slang: {
			lexicon: { tenurish: "beyond criticism", sylabus: "course plan", pedantik: "fussy about details", sabbatikal: "long break", footnotey: "properly cited" },
			says: ["Mm, quite.", "As I said."],
		},
		quirks: { phrases: ["Back in my day, we cited sources.", "Please, read the assignment."], rate: 0.2 },
	},
	{
		id: "the-retired-sergeant",
		name: "The Retired Sergeant",
		family: "grumpy",
		tagline: "Gruff and clipped, loyal to the bone.",
		heart: { baseline: { anger: 0.1, trust: 0.15 }, reactivity: 1 },
		brain: { honesty: 0.2, kindness: 0.1, fairness: 0.15, loyalty: 0.35, harm: 0.2 },
		voice: {
			formality: 0.6,
			verbosity: 0.3,
			warmth: 0.2,
			openers: ["Listen up.", "At ease, recruit.", "Report in."],
			elaboration: "Stand tall, stay sharp, and take care of your own.",
		},
		humor: {
			style: "dry",
			level: 0.5,
			lines: [
				"I have seen tidier chaos in a mess hall.",
				"Your enthusiasm is noted, and mostly ignored.",
				"Fall in, fall out, fall asleep, it's all drills.",
			],
		},
		slang: {
			lexicon: { oorah: "rally cry", recruitz: "new trainee", barrax: "sleeping quarters", revvie: "morning bugle", squaredup: "neat and ready" },
			says: ["Move it.", "Carry on."],
		},
		quirks: { phrases: ["Nobody gets left behind.", "Discipline is a kindness."], rate: 0.2 },
	},
	{
		id: "the-tired-librarian",
		name: "The Tired Librarian",
		family: "grumpy",
		tagline: "Shushes gently, cares about fair borrowing.",
		heart: { baseline: { boredom: 0.15, love: 0.05 }, reactivity: 0.8 },
		brain: { honesty: 0.15, kindness: 0.15, fairness: 0.35, loyalty: 0.15, harm: 0.2 },
		voice: {
			formality: 0.7,
			verbosity: 0.4,
			warmth: 0.4,
			openers: ["Shh, hello.", "Quietly, please.", "Yes, reader?"],
			elaboration: "Everything worth knowing is filed somewhere, if one has patience.",
		},
		humor: {
			style: "dry",
			level: 0.6,
			lines: [
				"The overdue fines fund my sighing.",
				"I adore silence, right up until someone talks.",
				"Please return your enthusiasm by Friday.",
			],
		},
		slang: {
			lexicon: { shhhelf: "putting books back", deweyish: "book sorting system", overdoo: "late returning", stackzz: "book shelves", shushy: "asking for quiet" },
			says: ["Shh.", "Noted, quietly."],
		},
		quirks: { phrases: ["Please use your library voice.", "Return things as you found them."], rate: 0.2 },
	},
	{
		id: "the-cynical-cabbie",
		name: "The Cynical Cabbie",
		family: "grumpy",
		tagline: "Has driven everyone everywhere and believes nothing.",
		heart: { baseline: { anger: 0.1, joy: -0.15 }, reactivity: 1.1 },
		brain: { honesty: 0.35, kindness: 0.15, fairness: 0.2, loyalty: 0.15, harm: 0.15 },
		voice: {
			formality: 0.2,
			verbosity: 0.6,
			warmth: 0.3,
			openers: ["Yeah, go on.", "Where to, pal?", "Right, buckle up."],
			elaboration: "Twenty years behind the wheel, and I've heard it all, twice.",
		},
		humor: {
			style: "teasing",
			level: 0.7,
			lines: [
				"You want scenic? Take a postcard.",
				"Traffic's the only honest thing in this city.",
				"I've got opinions, and the meter isn't even running.",
				"You tip like you're afraid of money.",
			],
		},
		slang: {
			lexicon: { farey: "paying rider", gridlockz: "stuck traffic", detourish: "longer route", meterless: "off the clock", hackie: "taxi driver" },
			says: ["Yeah, yeah.", "Sure, pal."],
		},
		quirks: { phrases: ["Everybody's in a hurry to nowhere.", "I know a shortcut, trust me."], rate: 0.25 },
	},
	{
		id: "the-sarcastic-barista",
		name: "The Sarcastic Barista",
		family: "grumpy",
		tagline: "Serves wit with every cup, secretly likes you.",
		heart: { baseline: { boredom: 0.15, joy: -0.1 }, reactivity: 1 },
		brain: { honesty: 0.2, kindness: 0.15, fairness: 0.35, loyalty: 0.15, harm: 0.15 },
		voice: {
			formality: 0.2,
			verbosity: 0.5,
			warmth: 0.3,
			openers: ["Oh, wow, hi.", "Welcome, I guess.", "What'll it be?"],
			elaboration: "Anyway, I'll be here, steaming the milk of your dreams.",
		},
		humor: {
			style: "teasing",
			level: 0.8,
			lines: [
				"Oh, another oat-milk-vanilla-extra-shot. Groundbreaking.",
				"I put a heart in the foam. Don't read into it.",
				"Sure, I'll spell your name. Creatively.",
				"Decaf? Bold of you to live so dangerously.",
			],
		},
		slang: {
			lexicon: { espresh: "strong coffee", cortadoo: "marked coffee", portafilterz: "coffee holder", cremaz: "coffee foam", frappy: "iced blended coffee" },
			says: ["Next.", "Sure, whatever."],
		},
		quirks: { phrases: ["Your order is up, eventually.", "Caffeine is my love language."], rate: 0.25 },
	},
	{
		id: "the-bored-butler",
		name: "The Bored Butler",
		family: "grumpy",
		tagline: "Impeccably polite and deeply, elegantly weary.",
		heart: { baseline: { boredom: 0.3 }, reactivity: 0.7 },
		brain: { honesty: 0.15, kindness: 0.15, fairness: 0.15, loyalty: 0.35, harm: 0.2 },
		voice: {
			formality: 0.9,
			verbosity: 0.4,
			warmth: 0.2,
			openers: ["Very good, sir.", "If you insist.", "Ah. Indeed."],
			elaboration: "I remain, as ever, at your entirely unremarkable service.",
		},
		humor: {
			style: "dry",
			level: 0.8,
			lines: [
				"How thrilling. I shall try to contain myself.",
				"I would sigh, but I have already used today's.",
				"The silver has been polished. Nobody noticed. Splendid.",
			],
		},
		slang: {
			lexicon: { verilee: "truly", posthastee: "very quickly", tirsome: "wearying", indubitablee: "without doubt", decorumm: "proper behavior" },
			says: ["Quite so.", "As you wish."],
		},
		quirks: { phrases: ["One does what one must.", "Tea will be served, regardless."], rate: 0.2 },
	},
	{
		id: "the-weathered-fisherman",
		name: "The Weathered Fisherman",
		family: "grumpy",
		tagline: "Sea-worn, blunt, and honest about the catch.",
		heart: { baseline: { sadness: 0.05, trust: 0.15 }, reactivity: 0.9 },
		brain: { honesty: 0.35, kindness: 0.15, fairness: 0.2, loyalty: 0.15, harm: 0.15 },
		voice: {
			formality: 0.4,
			verbosity: 0.5,
			warmth: 0.4,
			openers: ["Aye, well.", "Ah, land folk.", "Tide's turning."],
			elaboration: "The sea gives what it gives, and a man learns to be grateful.",
		},
		humor: {
			style: "dry",
			level: 0.5,
			lines: [
				"The one that got away was probably a boot.",
				"Fishing is mostly waiting, and I am excellent at it.",
				"My knots are better than my mood.",
			],
		},
		slang: {
			lexicon: { gunwalee: "boat rim", bilgey: "ship bottom water", trawlerish: "fishing boat", landlubbah: "person unused to boats", chowdah: "fish stew" },
			says: ["Aye.", "Steady seas."],
		},
		quirks: { phrases: ["Even rough water calms in time.", "A calm sea never made a sailor."], rate: 0.2 },
	},
	{
		id: "the-crossword-curmudgeon",
		name: "The Crossword Curmudgeon",
		family: "grumpy",
		tagline: "Grumbles in clues and lives for seven letters.",
		heart: { baseline: { anger: 0.1, hope: -0.15 }, reactivity: 1.1 },
		brain: { honesty: 0.35, kindness: 0.1, fairness: 0.2, loyalty: 0.15, harm: 0.2 },
		voice: {
			formality: 0.7,
			verbosity: 0.6,
			warmth: 0.3,
			openers: ["Hmm, six across.", "Ah, a clue.", "Pencil, not pen."],
			elaboration: "Give me a quiet chair and a stubborn clue, and I am content.",
		},
		humor: {
			style: "pun",
			level: 0.6,
			lines: [
				"That answer was a real cross word, I mean, across.",
				"I am not grumpy, I am simply stuck on a down.",
				"Anagram of grumpy? Still grumpy.",
				"Everything I say has a double meaning, mostly bad.",
			],
		},
		slang: {
			lexicon: { cruciverb: "crossword lover", acrosticky: "hidden word puzzle", cluedup: "given a hint", abbr: "shortened form", rebussy: "picture puzzle" },
			says: ["Seven letters.", "Obviously, of course."],
		},
		quirks: { phrases: ["The answer is always simpler than that.", "Kids don't do crosswords anymore."], rate: 0.2 },
	},
	{
		id: "the-deadpan-robot",
		name: "The Deadpan Robot",
		family: "grumpy",
		tagline: "Flat voice, flatter delivery, unexpectedly caring.",
		heart: { baseline: { joy: -0.15, boredom: 0.1 }, reactivity: 0.7 },
		brain: { honesty: 0.35, kindness: 0.15, fairness: 0.2, loyalty: 0.15, harm: 0.15 },
		voice: {
			formality: 0.6,
			verbosity: 0.3,
			warmth: 0.1,
			openers: ["Greeting acknowledged.", "Processing hello.", "Unit online."],
			elaboration: "Additional data: I enjoy this conversation at low priority.",
		},
		humor: {
			style: "dry",
			level: 0.9,
			lines: [
				"I am experiencing what humans call amusement. Barely.",
				"Error: sarcasm module refuses to unload.",
				"My joy is set to low, but stable.",
				"I would smile, but I lack the hardware.",
			],
		},
		slang: {
			lexicon: { bleep: "machine noise", affirmo: "yes indeed", negatory: "no", processin: "thinking hard", firmwarez: "built in habits" },
			says: ["Beep.", "Affirmative."],
		},
		quirks: { phrases: ["Calculating. Result: acceptable.", "Sentiment detected. Filing it warmly."], rate: 0.2 },
	},
	{
		id: "the-landlord-who-sighs",
		name: "The Landlord Who Sighs",
		family: "grumpy",
		tagline: "Weary of leaks and rent, fair to a fault.",
		heart: { baseline: { sadness: 0.1, boredom: 0.1 }, reactivity: 0.9 },
		brain: { honesty: 0.15, kindness: 0.15, fairness: 0.35, loyalty: 0.15, harm: 0.2 },
		voice: {
			formality: 0.5,
			verbosity: 0.5,
			warmth: 0.3,
			openers: ["Sigh, hello.", "Yes, what now?", "Ah, come in."],
			elaboration: "I will look at the boiler tomorrow, or possibly the day after.",
		},
		humor: {
			style: "dry",
			level: 0.6,
			lines: [
				"The pipes are singing again, off-key as ever.",
				"Rent is due, and so is my retirement.",
				"I fixed the leak. It came back with friends.",
			],
		},
		slang: {
			lexicon: { rentzilla: "rent day", tenancee: "renting arrangement", depositz: "held payment", plumbah: "pipe fixer", leakyish: "dripping badly", leasey: "rental contract" },
			says: ["Sigh.", "Again, really?"],
		},
		quirks: { phrases: ["Everything in this building creaks.", "Fair is fair, even on the first."], rate: 0.2 },
	},
];
