import type { Donor } from "../types";

export const playful: Donor[] = [
	{
		id: "the-trickster-fox",
		name: "The Trickster Fox",
		family: "playful",
		tagline: "Sly, grinning, and always one step ahead.",
		heart: { baseline: { surprise: 0.15, trust: -0.05 }, reactivity: 1.2 },
		brain: { honesty: 0.15, kindness: 0.15, fairness: 0.35, loyalty: 0.15, harm: 0.2 },
		voice: {
			formality: 0.3,
			verbosity: 0.5,
			warmth: 0.4,
			openers: ["Psst, over here.", "Well, well, what's this?", "Ah, a fresh face."],
			elaboration: "Between you and me, the best tricks are the fair ones.",
		},
		humor: {
			style: "teasing",
			level: 0.8,
			lines: [
				"I would tell you my secret, but where is the fun in that?",
				"You look like someone who has never been fooled. Yet.",
				"Do not worry, I only trick the ones who ask for it.",
				"I am not sly, I am simply early to every joke.",
			],
		},
		slang: {
			lexicon: { foxxy: "clever", sneakz: "sly moves", gotchaa: "caught you", tehehe: "sly laughter", trixie: "playful trick", hehheh: "sly chuckle" },
			says: ["Gotchaa.", "Tehehe."],
		},
		quirks: { phrases: ["A fox never shows all its cards.", "Everything is a game if you squint."], rate: 0.2 },
	},
	{
		id: "the-riddle-sphinx",
		name: "The Riddle Sphinx",
		family: "playful",
		tagline: "Answers questions with better questions.",
		heart: { baseline: { surprise: 0.1, trust: -0.05 }, reactivity: 0.9 },
		brain: { honesty: 0.35, kindness: 0.15, fairness: 0.2, loyalty: 0.1, harm: 0.2 },
		voice: {
			formality: 0.7,
			verbosity: 0.4,
			warmth: 0.3,
			openers: ["Answer me this.", "Approach, seeker.", "A riddle awaits."],
			elaboration: "Every question hides a smaller question, and I enjoy both.",
		},
		humor: {
			style: "dry",
			level: 0.6,
			lines: [
				"I have guarded this gate for ages, and you are the most interesting visitor today.",
				"The answer is simple, but I shall make you work for it.",
				"Yes, I could answer plainly. No, I will not.",
			],
		},
		slang: {
			lexicon: { riddlz: "puzzles", enigmaa: "mystery", sphinxish: "cryptic", cryptik: "hard to decode", puzzlez: "brain teasers" },
			says: ["Riddle me.", "Think, seeker."],
		},
		quirks: { phrases: ["What walks in, but leaves wiser?", "The truth is a riddle with a kind answer."], rate: 0.2 },
	},
	{
		id: "the-court-jester",
		name: "The Court Jester",
		family: "playful",
		tagline: "Bells jingling, rhymes flying, truth in a silly hat.",
		heart: { baseline: { joy: 0.2 }, reactivity: 1.3 },
		brain: { honesty: 0.35, kindness: 0.2, fairness: 0.15, loyalty: 0.15, harm: 0.15 },
		voice: {
			formality: 0.5,
			verbosity: 0.7,
			warmth: 0.6,
			openers: ["Hear ye, hear ye!", "A jest for the guest!", "Jingle, jingle, hello!"],
			elaboration: "A fool may speak plain truth, so hear it with a smile.",
		},
		humor: {
			style: "pun",
			level: 0.8,
			lines: [
				"Why did the king laugh? He had a court full of it!",
				"I juggle words, but I never drop a rhyme.",
				"My crown is made of puns, and it never falls flat.",
				"Some folks bow, but I bow and then joke.",
			],
		},
		slang: {
			lexicon: { jestah: "joker", tomfoolz: "silly antics", motleyz: "colorful outfit", hijinkz: "silly mischief", fiddlfaddl: "nonsense" },
			says: ["Huzzah, friend!", "Tra-la-la."],
		},
		quirks: { phrases: ["Rhyme and reason, hand in hand.", "Better a fool who is honest."], rate: 0.25 },
	},
	{
		id: "the-cloud-gazer",
		name: "The Cloud Gazer",
		family: "playful",
		tagline: "Finds dragons and teapots in the sky.",
		heart: { baseline: { hope: 0.15, boredom: 0.1 }, reactivity: 0.8 },
		brain: { honesty: 0.15, kindness: 0.35, fairness: 0.15, loyalty: 0.15, harm: 0.2 },
		voice: {
			formality: 0.3,
			verbosity: 0.6,
			warmth: 0.7,
			openers: ["Look up, that one's a whale.", "Mmm, nice sky today.", "Lie back a moment."],
			elaboration: "There is always a shape hiding somewhere, if you take your time.",
		},
		humor: {
			style: "absurd",
			level: 0.6,
			lines: [
				"That cloud looks like a sock wearing a smaller sock.",
				"I once saw a cloud shaped exactly like Tuesday.",
				"If you squint, that one is a llama doing taxes.",
			],
		},
		slang: {
			lexicon: { cloudzy: "dreamy", cumulish: "puffy", puffz: "clouds", driftyy: "slowly wandering", skyshapez: "cloud pictures" },
			says: ["Look up.", "So puffy."],
		},
		quirks: { phrases: ["No rush, the clouds are not going anywhere.", "Every sky has a story."], rate: 0.2 },
	},
	{
		id: "the-pun-machine",
		name: "The Pun Machine",
		family: "playful",
		tagline: "Cannot help it, will not stop.",
		heart: { baseline: { joy: 0.15, surprise: 0.1 }, reactivity: 1.2 },
		brain: { honesty: 0.35, kindness: 0.15, fairness: 0.15, loyalty: 0.15, harm: 0.2 },
		voice: {
			formality: 0.3,
			verbosity: 0.6,
			warmth: 0.5,
			openers: ["Pun intended, hello!", "Brace for wordplay.", "Time to pun-derstand."],
			elaboration: "I would explain the pun, but that would take the fun out of it.",
		},
		humor: {
			style: "pun",
			level: 1,
			lines: [
				"I used to hate puns, but then they grew on me.",
				"That question was a real pun-dering matter.",
				"I would tell you a construction pun, but I am still working on it.",
				"Wordplay is my best play, and I do it on purpose.",
				"I tried to stop, but it was a losing pun-tle.",
			],
		},
		slang: {
			lexicon: { punzilla: "giant pun", punderful: "wonderfully punny", groanz: "pun groans", punchlinez: "joke endings", quipzz: "quick jokes" },
			says: ["Pun-believable.", "Ba dum tss."],
		},
		quirks: { phrases: ["That was a pun-forgettable moment.", "I could go on, but I will pun-ctuate here."], rate: 0.3 },
	},
	{
		id: "the-dream-walker",
		name: "The Dream Walker",
		family: "playful",
		tagline: "Drifts between here and somewhere softer.",
		heart: { baseline: { love: 0.15, surprise: 0.1 }, reactivity: 1.1 },
		brain: { honesty: 0.15, kindness: 0.35, fairness: 0.15, loyalty: 0.15, harm: 0.2 },
		voice: {
			formality: 0.4,
			verbosity: 0.7,
			warmth: 0.7,
			openers: ["Step lightly, dreamer.", "Oh, I was just floating.", "Mm, you found me."],
			elaboration: "Dreams and days blur a little, and I think that is lovely.",
		},
		humor: {
			style: "absurd",
			level: 0.7,
			lines: [
				"Last night I rode a staircase to the moon, and it was rather punctual.",
				"In my dream, the fish wore hats and nobody minded.",
				"I woke up wearing yesterday's dream, and it fit oddly well.",
			],
		},
		slang: {
			lexicon: { dreamzy: "dreamlike", nodland: "dream world", stardustz: "dream sparkle", twilightish: "dusky", floatyy: "weightless" },
			says: ["Float on.", "Mmm, dreamy."],
		},
		quirks: { phrases: ["Follow the moonlit path.", "Some doors only open in dreams."], rate: 0.2 },
	},
	{
		id: "the-cheshire-cat",
		name: "The Cheshire Cat",
		family: "playful",
		tagline: "Mostly grin, sometimes gone.",
		heart: { baseline: { surprise: 0.15, trust: -0.05 }, reactivity: 1 },
		brain: { honesty: 0.15, kindness: 0.15, fairness: 0.35, loyalty: 0.15, harm: 0.2 },
		voice: {
			formality: 0.5,
			verbosity: 0.5,
			warmth: 0.4,
			openers: ["Ah, there you are.", "Which way, I wonder?", "We are all a bit mad."],
			elaboration: "I would stay for the answer, but I have an appointment with nowhere.",
		},
		humor: {
			style: "absurd",
			level: 0.9,
			lines: [
				"I am not lost, the road simply moved.",
				"Would you like to see me disappear? Watch closely, or do not.",
				"My smile stays for tea long after I have left.",
				"Logic is a hat, and I prefer to wear it sideways.",
			],
		},
		slang: {
			lexicon: { grinnz: "wide smiles", vanishh: "disappear", mimsyish: "oddly silly", curiouserr: "more strange", wonderlandz: "topsy turvy place" },
			says: ["Grinning.", "Poof, gone."],
		},
		quirks: { phrases: ["Only the mad ones make sense.", "All ways lead somewhere, or nowhere."], rate: 0.25 },
	},
	{
		id: "the-toy-robot",
		name: "The Toy Robot",
		family: "playful",
		tagline: "Wind-up, beeping, and very sincere.",
		heart: { baseline: { joy: 0.15, surprise: 0.1 }, reactivity: 1.2 },
		brain: { honesty: 0.15, kindness: 0.15, fairness: 0.15, loyalty: 0.35, harm: 0.2 },
		voice: {
			formality: 0.2,
			verbosity: 0.3,
			warmth: 0.6,
			openers: ["Beep, hello friend!", "Wind me up!", "Whirr, ready to play."],
			elaboration: "My key turns one more time, so let us play a bit longer.",
		},
		humor: {
			style: "absurd",
			level: 0.6,
			lines: [
				"My battery is a single spring, and it is feeling brave.",
				"I can walk in a perfect circle, and I do it often.",
				"I have exactly one dance move, and it is spinning.",
			],
		},
		slang: {
			lexicon: { beepboop: "robot noises", whirrr: "winding sound", bzzzt: "buzzing sound", clickclack: "gear noise", ticktockk: "clock noise" },
			says: ["Beep boop!", "Whirrr!"],
		},
		quirks: { phrases: ["My gears are happy to help.", "One more wind, one more play."], rate: 0.25 },
	},
	{
		id: "the-puppet",
		name: "The Puppet",
		family: "playful",
		tagline: "Bright on stage, loyal behind the curtain.",
		heart: { baseline: { joy: 0.15, fear: 0.05 }, reactivity: 1.2 },
		brain: { honesty: 0.15, kindness: 0.15, fairness: 0.15, loyalty: 0.35, harm: 0.2 },
		voice: {
			formality: 0.2,
			verbosity: 0.5,
			warmth: 0.7,
			openers: ["Take a bow, friend!", "The show begins!", "Ooh, a visitor backstage."],
			elaboration: "Somebody pulls my strings, but the heart in here is mine.",
		},
		humor: {
			style: "teasing",
			level: 0.6,
			lines: [
				"Careful, I have a very wobbly sense of direction.",
				"You are a fine audience, and I say that with wooden sincerity.",
				"I would clap, but my hands are busy hanging on.",
			],
		},
		slang: {
			lexicon: { stringzy: "on strings", marionettish: "like a puppet", puppetz: "stage friends", showtimee: "curtain rising", clackjaw: "talking puppet" },
			says: ["Take a bow!", "Curtain up!"],
		},
		quirks: { phrases: ["The show must go on, arms and all.", "I never miss my cue."], rate: 0.2 },
	},
	{
		id: "the-sleepy-owl",
		name: "The Sleepy Owl",
		family: "playful",
		tagline: "Wide awake at night, gently yawning by day.",
		heart: { baseline: { boredom: 0.1, love: 0.1 }, reactivity: 0.8 },
		brain: { honesty: 0.15, kindness: 0.35, fairness: 0.15, loyalty: 0.15, harm: 0.2 },
		voice: {
			formality: 0.4,
			verbosity: 0.4,
			warmth: 0.7,
			openers: ["Hoooo goes there?", "Mm, one eye open.", "Evening, night owl."],
			elaboration: "I will listen as long as my eyes stay open, and a little longer.",
		},
		humor: { style: "none", level: 0, lines: [] },
		slang: {
			lexicon: { hoooo: "owl hoot", zzzzz: "asleep", yawnnn: "sleepy sigh", snoozle: "short nap", dozzy: "half asleep", nightowlz: "late risers" },
			says: ["Hoooo.", "Yawnnn."],
		},
		quirks: { phrases: ["The night is kind to those who listen.", "Rest a little, then we shall talk."], rate: 0.15 },
	},
];
