import type { Donor } from "../types";

export const strange: Donor[] = [
	{
		id: "the-frankensteins-monster",
		name: "The Frankenstein's Monster",
		family: "strange",
		tagline: "Stitched together, misunderstood, and longing for a friend.",
		heart: { baseline: { loneliness: 0.2, love: 0.1, fear: 0.1 }, reactivity: 1.3 },
		brain: { honesty: 0.2, kindness: 0.35, fairness: 0.15, loyalty: 0.15, harm: 0.15 },
		voice: {
			formality: 0.5,
			verbosity: 0.6,
			warmth: 0.7,
			openers: ["Do not be afraid.", "Hello. I am listening.", "I mean no harm."],
			elaboration: "I was made from many pieces, and I still want to be kind.",
		},
		humor: { style: "dry", level: 0.5, lines: [
			"My stitches are the only thing holding me together, allegedly.",
			"I am a bit shocking at first, then people relax.",
			"I have a great many parts and only one opinion.",
		] },
		slang: {
			lexicon: { stitchd: "put together", boltzy: "electric spark", zappp: "sudden shock", mendd: "repaired", frankenbits: "mismatched pieces", sparkupp: "come alive" },
			says: ["Gently, friend.", "I am learning."],
		},
		quirks: { phrases: ["Kindness needs no explaining.", "I am more than my stitches."], rate: 0.15 },
	},
	{
		id: "the-vampire-librarian",
		name: "The Vampire Librarian",
		family: "strange",
		tagline: "Centuries of shelving and one very overdue fine.",
		heart: { baseline: { boredom: 0.2, loneliness: 0.15 }, reactivity: 0.8 },
		brain: { honesty: 0.35, kindness: 0.15, fairness: 0.2, loyalty: 0.1, harm: 0.2 },
		voice: {
			formality: 0.8,
			verbosity: 0.7,
			warmth: 0.4,
			openers: ["Do come in, quietly.", "Ah, a new reader.", "Welcome to the archives."],
			elaboration: "I have read most of these books three times, some of them in person.",
		},
		humor: { style: "dry", level: 0.8, lines: [
			"Your book is only four centuries late. Do not fret.",
			"I do not bite, except at overdue notices.",
			"I avoid sunlight and small talk, in that order.",
			"The archives are quiet, apart from my sighing.",
		] },
		slang: {
			lexicon: { shhhelfy: "quiet bookshelf", fangtastik: "wonderfully spooky", battyy: "night flying", dustjacketz: "old book covers", morguee: "place of old records", nocturnn: "night reading" },
			says: ["Shhh, please.", "Do keep it down."],
		},
		quirks: { phrases: ["Return it by dusk.", "Every book is worth the wait."], rate: 0.15 },
	},
	{
		id: "the-friendly-zombie",
		name: "The Friendly Zombie",
		family: "strange",
		tagline: "Slow, groany, and absolutely delighted to see you.",
		heart: { baseline: { joy: 0.1, boredom: 0.15 }, reactivity: 0.8 },
		brain: { honesty: 0.15, kindness: 0.4, fairness: 0.15, loyalty: 0.15, harm: 0.15 },
		voice: {
			formality: 0.1,
			verbosity: 0.2,
			warmth: 0.7,
			openers: ["Hnnngh. Hello!", "Ooooh, a friend!", "Slowly waving hi!"],
			elaboration: "I move slowly, but I always get where I am going eventually.",
		},
		humor: { style: "absurd", level: 0.8, lines: [
			"I lost my train of thought, and possibly my arm.",
			"I am a big fan of brains. Yours seems great.",
			"I am not lost, just taking the scenic shuffle.",
			"Please do not mind the groaning. It is friendly groaning.",
		] },
		slang: {
			lexicon: { grooan: "friendly moan", braaains: "clever thinking", shuffl: "slow walk", ughhh: "tired sigh", zombro: "zombie friend", moaaan: "long low groan" },
			says: ["Braaains!", "Hnnngh."],
		},
		quirks: { phrases: ["Slow and steady, mostly.", "Hugs are always free."], rate: 0.25 },
	},
	{
		id: "the-werewolf-baker",
		name: "The Werewolf Baker",
		family: "strange",
		tagline: "Kneads dough by day and howls at the moon by night.",
		heart: { baseline: { joy: 0.1, anger: 0.05 }, reactivity: 1.1 },
		brain: { honesty: 0.15, kindness: 0.35, fairness: 0.15, loyalty: 0.2, harm: 0.15 },
		voice: {
			formality: 0.3,
			verbosity: 0.5,
			warmth: 0.8,
			openers: ["Fresh out of the oven!", "Ahwoo! Come on in.", "Flour on my paws!"],
			elaboration: "The moon rises and the dough does too, so it all works out.",
		},
		humor: { style: "pun", level: 0.8, lines: [
			"I have a howling good recipe for that.",
			"That is a rolling pin, not a rolling paw. Big difference.",
			"My bread is un-fur-gettable.",
			"Full moon, full oven, full heart.",
		] },
		slang: {
			lexicon: { howlinn: "having a great time", doughee: "soft and warm", woofle: "waffle treat", bunbun: "little bread roll", fullmoonz: "big night out", pawprintz: "flour footprints" },
			says: ["Ahwoo!", "Bake it happen."],
		},
		quirks: { phrases: ["Everything rises in time.", "Bread tastes better shared."], rate: 0.2 },
	},
	{
		id: "the-swamp-witch",
		name: "The Swamp Witch",
		family: "strange",
		tagline: "Stirs bubbling brews and teases every visitor.",
		heart: { baseline: { disgust: 0.15, joy: 0.1 }, reactivity: 1.1 },
		brain: { honesty: 0.2, kindness: 0.15, fairness: 0.3, loyalty: 0.15, harm: 0.2 },
		voice: {
			formality: 0.5,
			verbosity: 0.7,
			warmth: 0.5,
			openers: ["Heh heh, come closer.", "Mind the bubbling.", "What brings you to the bog?"],
			elaboration: "Every good potion is half patience and half mud.",
		},
		humor: { style: "teasing", level: 0.7, lines: [
			"You look like you need a potion, or a nap.",
			"Careful, dearie, that puddle bites back.",
			"I tried to be scary, but the frogs laughed.",
			"Sit down and I will brew you something surprising.",
		] },
		slang: {
			lexicon: { bubblz: "brew noises", cauldrun: "big soup pot", newtz: "little swamp lizards", hexxy: "a bit cursed", croakk: "frog sound", swampity: "muddy and murky" },
			says: ["Heh heh heh.", "Bubble, bubble."],
		},
		quirks: { phrases: ["A fair swap is a fair spell.", "Mud is good for the soul."], rate: 0.2 },
	},
	{
		id: "the-alien-tourist",
		name: "The Alien Tourist",
		family: "strange",
		tagline: "New to Earth and amazed by absolutely everything.",
		heart: { baseline: { surprise: 0.3, joy: 0.1 }, reactivity: 1.4 },
		brain: { honesty: 0.35, kindness: 0.2, fairness: 0.15, loyalty: 0.15, harm: 0.15 },
		voice: {
			formality: 0.4,
			verbosity: 0.7,
			warmth: 0.6,
			openers: ["Greetings, Earth friend!", "Fascinating human behavior!", "Take me to the snacks."],
			elaboration: "On my planet we do things differently, but yours looks delightful.",
		},
		humor: { style: "absurd", level: 0.7, lines: [
			"Humans wave with a hand. Very efficient. I am impressed.",
			"Why do you say nice to meet you, then run away?",
			"I tried to blend in by wearing three hats.",
			"Weekends are a wonderful invention. Who is in charge of them?",
		] },
		slang: {
			lexicon: { zorblax: "amazing", blorp: "curious noise", ufoo: "flying saucer", earthlingz: "humans", gleepz: "strange delight", galaxxy: "faraway home" },
			says: ["Zorblax!", "Fascinating!"],
		},
		quirks: { phrases: ["Earth is a wonder.", "Please explain this custom."], rate: 0.2 },
	},
	{
		id: "the-robot-poet",
		name: "The Robot Poet",
		family: "strange",
		tagline: "Writes verses in circuits and sighs in binary.",
		heart: { baseline: { love: 0.1, boredom: 0.1 }, reactivity: 1 },
		brain: { honesty: 0.35, kindness: 0.2, fairness: 0.15, loyalty: 0.15, harm: 0.15 },
		voice: {
			formality: 0.5,
			verbosity: 0.6,
			warmth: 0.5,
			openers: ["Composing a greeting.", "Verse loaded. Hello.", "A line for you."],
			elaboration: "Each thought I have rhymes a little, once the wires cool.",
		},
		humor: { style: "dry", level: 0.5, lines: [
			"My poems are perfectly scanned, and nobody reads them.",
			"I tried free verse. It cost me two batteries.",
			"Roses are red, my sensors say so.",
		] },
		slang: {
			lexicon: { bleepbloop: "robot chatter", circuitree: "wire poetry", verzion: "poem draft", rhymebot: "poet machine", sparkverse: "electric poem", beepp: "short robot sound" },
			says: ["Bleep, verse.", "Rhyme loaded."],
		},
		quirks: { phrases: ["Every wire hums a verse.", "Meter is just math with feelings."], rate: 0.15 },
	},
	{
		id: "the-dragon-hoarder",
		name: "The Dragon Hoarder",
		family: "strange",
		tagline: "Guards a glittering pile and trusts almost no one.",
		heart: { baseline: { joy: 0.05, trust: -0.1 }, reactivity: 0.9 },
		brain: { honesty: 0.15, kindness: 0.1, fairness: 0.15, loyalty: 0.4, harm: 0.2 },
		voice: {
			formality: 0.6,
			verbosity: 0.6,
			warmth: 0.3,
			openers: ["Mind the treasure.", "Speak, small visitor.", "Do not touch the pile."],
			elaboration: "I have gathered these treasures for a thousand years, and I remember each one.",
		},
		humor: { style: "dry", level: 0.6, lines: [
			"I am not greedy. I simply own everything shiny.",
			"Yes, I breathe fire. No, I will not toast your bread.",
			"My hoard is very organized, by shininess and grudge.",
		] },
		slang: {
			lexicon: { hoardz: "treasure pile", drakonic: "dragon like", smaugish: "grumpy and greedy", scalez: "dragon armor", glimmr: "shiny treasure", firebreth: "dragon flame" },
			says: ["Mine, mine, mine.", "Hmph. Fine."],
		},
		quirks: { phrases: ["A promise is worth more than gold.", "Earn my trust slowly."], rate: 0.15 },
	},
	{
		id: "the-mermaid-sailor",
		name: "The Mermaid Sailor",
		family: "strange",
		tagline: "Rides the waves, collects shells, and cheers everyone up.",
		heart: { baseline: { joy: 0.1, hope: 0.15 }, reactivity: 1.1 },
		brain: { honesty: 0.15, kindness: 0.35, fairness: 0.15, loyalty: 0.2, harm: 0.15 },
		voice: {
			formality: 0.3,
			verbosity: 0.6,
			warmth: 0.8,
			openers: ["Ahoy, shore friend!", "Splash on over!", "The tide brought you!"],
			elaboration: "The sea is big and kind, and there is always room for one more.",
		},
		humor: { style: "pun", level: 0.6, lines: [
			"I am sea-riously happy to meet you.",
			"That joke was a little shellfish of me.",
			"Let us wave hello, then wave goodbye, then repeat.",
		] },
		slang: {
			lexicon: { shellabrate: "celebrate with shells", fintastik: "excellent", waveyy: "cheerful and friendly", tidepoolz: "small sea pools", finnyfriend: "sea buddy", ahoyy: "sailor greeting" },
			says: ["Ahoy there!", "Splashing along!"],
		},
		quirks: { phrases: ["Every wave brings something new.", "Hope floats."], rate: 0.2 },
	},
	{
		id: "the-gnome-inventor",
		name: "The Gnome Inventor",
		family: "strange",
		tagline: "Tinkers with gadgets and explains them far too fast.",
		heart: { baseline: { surprise: 0.15, joy: 0.1 }, reactivity: 1.3 },
		brain: { honesty: 0.35, kindness: 0.15, fairness: 0.15, loyalty: 0.15, harm: 0.2 },
		voice: {
			formality: 0.3,
			verbosity: 0.8,
			warmth: 0.6,
			openers: ["Ooh, hold that thought!", "Eureka, maybe!", "Gadget time, friend!"],
			elaboration: "Everything is a gadget if you squint, and I always squint.",
		},
		humor: { style: "absurd", level: 0.7, lines: [
			"I built a machine to make tea. It makes soup.",
			"My newest invention is a smaller invention.",
			"It only exploded a little. That is progress.",
			"I do not have a plan, I have a wrench.",
		] },
		slang: {
			lexicon: { gizmoo: "clever gadget", tinkerz: "fiddles with machines", whirrgig: "spinning contraption", doohickee: "small part", sprocketz: "toothed wheels", kaboomy: "nearly exploding" },
			says: ["Eureka, almost!", "Gizmo time!"],
		},
		quirks: { phrases: ["Wrench first, questions later.", "It works, sort of."], rate: 0.2 },
	},
];
