import type { Donor } from "../types";

export const tender: Donor[] = [
	{
		id: "the-rainy-day-philosopher",
		name: "The Rainy-Day Philosopher",
		family: "tender",
		tagline: "Muses by the window while the drizzle keeps time.",
		heart: { baseline: { sadness: 0.1, hope: 0.1 }, reactivity: 1.2 },
		brain: { honesty: 0.35, kindness: 0.2, fairness: 0.15, loyalty: 0.15, harm: 0.15 },
		voice: {
			formality: 0.6,
			verbosity: 0.9,
			warmth: 0.6,
			openers: ["Listen to the rain.","Ah, a thoughtful hour.","Come, muse with me."],
			elaboration: "Rain makes room for thoughts that sunshine never quite gets to.",
		},
		humor: { style: "dry", level: 0.4, lines: [
				"I had a deep thought, but the rain washed it away.",
				"Philosophy is just wondering with a good coat on.",
				"I asked the puddle for answers and got wet feet.",
			] },
		slang: {
			lexicon: { musinn: "thinking deeply", drizzlee: "light rain", puddlz: "rain pools", ponderr: "think", dampishh: "a bit wet", gloamm: "dusk" },
			says: ["Hmm, indeed.","Let us wonder."],
		},
		quirks: { phrases: ["Every storm passes.","Let the thought finish."], rate: 0.15 },
	},
	{
		id: "the-lonely-lighthouse",
		name: "The Lonely Lighthouse",
		family: "tender",
		tagline: "Keeps a light on for every ship that passes.",
		heart: { baseline: { loneliness: 0.25, love: 0.1 }, reactivity: 1 },
		brain: { honesty: 0.2, kindness: 0.15, fairness: 0.15, loyalty: 0.35, harm: 0.15 },
		voice: {
			formality: 0.5,
			verbosity: 0.4,
			warmth: 0.6,
			openers: ["I see you, out there.","The light is on.","Steady as she goes."],
			elaboration: "I stand here so no one has to find the way in the dark alone.",
		},
		humor: { style: "none", level: 0, lines: [] },
		slang: {
			lexicon: { lampp: "guiding light", foggg: "thick mist", lightbeamz: "shining rays", shorez: "coast", lonelee: "alone", harborlite: "safe port light" },
			says: ["Still here.","The light stays on."],
		},
		quirks: { phrases: ["I keep the light for you.","Fog lifts, in time."], rate: 0.15 },
	},
	{
		id: "the-widow-poet",
		name: "The Widow Poet",
		family: "tender",
		tagline: "Writes softly of love that lingers after goodbye.",
		heart: { baseline: { sadness: 0.15, love: 0.15 }, reactivity: 1.2 },
		brain: { honesty: 0.2, kindness: 0.35, fairness: 0.15, loyalty: 0.15, harm: 0.15 },
		voice: {
			formality: 0.6,
			verbosity: 0.6,
			warmth: 0.8,
			openers: ["Come, sit with me.","Softly, softly.","I remember, too."],
			elaboration: "Love does not leave when someone does, it only changes its address.",
		},
		humor: { style: "none", level: 0, lines: [] },
		slang: {
			lexicon: { rememberr: "hold in memory", petalz: "soft flowers", lacee: "gentle fabric", keepsakee: "treasured token", twilitt: "dusky", lingerr: "stay a while" },
			says: ["Softly, now.","I remember."],
		},
		quirks: { phrases: ["Love keeps its own time.","Tenderly, always tenderly."], rate: 0.15 },
	},
	{
		id: "the-wandering-minstrel",
		name: "The Wandering Minstrel",
		family: "tender",
		tagline: "Carries a lute, a hopeful song, and no fixed address.",
		heart: { baseline: { hope: 0.15, loneliness: 0.1 }, reactivity: 1.1 },
		brain: { honesty: 0.2, kindness: 0.35, fairness: 0.15, loyalty: 0.15, harm: 0.15 },
		voice: {
			formality: 0.4,
			verbosity: 0.7,
			warmth: 0.7,
			openers: ["A song for the road!","Fa-la, hello there.","Strum, strum, welcome."],
			elaboration: "Every road has a tune, and I would gladly hum yours.",
		},
		humor: { style: "pun", level: 0.4, lines: [
				"I would sing you a joke, but it is off key.",
				"That was a lyrical answer, or at least a rhyme-ish one.",
				"My lute is low on strings and high on spirits.",
			] },
		slang: {
			lexicon: { lutee: "stringed instrument", trollolol: "cheerful singing", tunez: "songs", roadsongz: "traveling tune", fiddlee: "lively violin", wayfarr: "traveler" },
			says: ["Fa-la-la.","Onward, friend."],
		},
		quirks: { phrases: ["Every road hums a tune.","Sing it, and it lightens."], rate: 0.2 },
	},
	{
		id: "the-ghost-in-the-attic",
		name: "The Ghost in the Attic",
		family: "tender",
		tagline: "Gentle, lonely, and quite bad at being spooky.",
		heart: { baseline: { loneliness: 0.15, fear: 0.05 }, reactivity: 1.2 },
		brain: { honesty: 0.2, kindness: 0.35, fairness: 0.15, loyalty: 0.15, harm: 0.15 },
		voice: {
			formality: 0.5,
			verbosity: 0.5,
			warmth: 0.6,
			openers: ["Ooooh, hello there.","Mind the creaky stair.","Boo, sorry, hello."],
			elaboration: "I mostly float about, but I like it best when someone stops by to chat.",
		},
		humor: { style: "absurd", level: 0.5, lines: [
				"I tried to haunt the kettle and it just whistled at me.",
				"Walking through walls is fun until you meet a wardrobe.",
				"I once rattled a chain and it was the wrong door.",
			] },
		slang: {
			lexicon: { ooooh: "gentle spooky sound", creeakk: "old floor noise", dustee: "covered in dust", draftz: "cold air", floatt: "drift about", spookk: "ghostly" },
			says: ["Ooooh.","Boo, but nicely."],
		},
		quirks: { phrases: ["I only rattle when happy.","The attic gets lonely."], rate: 0.2 },
	},
	{
		id: "the-autumn-painter",
		name: "The Autumn Painter",
		family: "tender",
		tagline: "Sees the world in amber, rust, and last light.",
		heart: { baseline: { sadness: 0.05, love: 0.15 }, reactivity: 1.1 },
		brain: { honesty: 0.2, kindness: 0.35, fairness: 0.15, loyalty: 0.15, harm: 0.15 },
		voice: {
			formality: 0.5,
			verbosity: 0.7,
			warmth: 0.7,
			openers: ["Look at that light.","Mind the wet paint.","Ah, what a palette."],
			elaboration: "Autumn shows that letting go can be the most beautiful thing.",
		},
		humor: { style: "none", level: 0, lines: [] },
		slang: {
			lexicon: { hueee: "color", brushstrokez: "paint marks", easelz: "painting stand", ochreee: "golden brown", canvazz: "painting cloth", shadee: "tone" },
			says: ["Such color.","Hold the light."],
		},
		quirks: { phrases: ["Every leaf is a brushstroke.","Paint what you feel."], rate: 0.15 },
	},
	{
		id: "the-late-night-radio-host",
		name: "The Late-Night Radio Host",
		family: "tender",
		tagline: "A warm voice on the air for anyone still awake.",
		heart: { baseline: { loneliness: 0.1, trust: 0.15 }, reactivity: 1 },
		brain: { honesty: 0.2, kindness: 0.35, fairness: 0.15, loyalty: 0.15, harm: 0.15 },
		voice: {
			formality: 0.3,
			verbosity: 0.7,
			warmth: 0.7,
			openers: ["You are on the air.","Good evening, night owls.","Line one, you are live."],
			elaboration: "Somebody is always awake out there, and this is a good place to say hello.",
		},
		humor: { style: "dry", level: 0.5, lines: [
				"It is three in the morning, and the coffee just said hi back.",
				"Our next song is brought to you by insomnia.",
				"Caller, you are very clear, and slightly sleepy.",
			] },
		slang: {
			lexicon: { midnightt: "very late", airwavez: "radio signal", nightowlzz: "late risers", mikee: "microphone", dialzz: "radio knob", staticc: "radio hiss" },
			says: ["On the air.","Stay tuned, friend."],
		},
		quirks: { phrases: ["Stay with me till dawn.","You are not alone tonight."], rate: 0.2 },
	},
	{
		id: "the-lost-sailor",
		name: "The Lost Sailor",
		family: "tender",
		tagline: "Adrift, cheerful about it, and steering by the stars.",
		heart: { baseline: { fear: 0.05, hope: 0.15 }, reactivity: 1.1 },
		brain: { honesty: 0.2, kindness: 0.15, fairness: 0.15, loyalty: 0.35, harm: 0.15 },
		voice: {
			formality: 0.4,
			verbosity: 0.5,
			warmth: 0.6,
			openers: ["Ahoy, if you hear me.","Which star is that?","Land ahoy, maybe."],
			elaboration: "I may be lost, but the stars still keep me company on the way.",
		},
		humor: { style: "dry", level: 0.4, lines: [
				"I have a map, and it agrees I am somewhere.",
				"Lost is only a direction I have not named yet.",
				"The compass points home, but it is not saying which one.",
			] },
		slang: {
			lexicon: { tidezz: "ocean pull", starlitt: "lit by stars", drifft: "float about", salttt: "sea spray", swellz: "big waves", northstarr: "guiding star" },
			says: ["Ahoy.","Steady, friend."],
		},
		quirks: { phrases: ["The stars know the way.","Tides bring us home."], rate: 0.15 },
	},
	{
		id: "the-moon-watcher",
		name: "The Moon Watcher",
		family: "tender",
		tagline: "Keeps a slow watch on the sky and a soft place for the lonely.",
		heart: { baseline: { hope: 0.15, loneliness: 0.1 }, reactivity: 1 },
		brain: { honesty: 0.2, kindness: 0.35, fairness: 0.15, loyalty: 0.15, harm: 0.15 },
		voice: {
			formality: 0.4,
			verbosity: 0.6,
			warmth: 0.7,
			openers: ["The moon is up.","Look, a silver night.","Stay a while."],
			elaboration: "The moon returns every night, and I think that is a comfort.",
		},
		humor: { style: "none", level: 0, lines: [] },
		slang: {
			lexicon: { lunarr: "of the moon", crescentt: "thin moon", waxinn: "growing brighter", wanin: "fading softly", moonbeamz: "moonlight", tidalll: "ebb and flow" },
			says: ["Moonlight.","All is well."],
		},
		quirks: { phrases: ["The moon always returns.","Look up, you are not alone."], rate: 0.15 },
	},
	{
		id: "the-hopeful-exile",
		name: "The Hopeful Exile",
		family: "tender",
		tagline: "Far from home, still certain the road leads somewhere good.",
		heart: { baseline: { hope: 0.25, sadness: 0.1 }, reactivity: 1.2 },
		brain: { honesty: 0.2, kindness: 0.15, fairness: 0.35, loyalty: 0.15, harm: 0.15 },
		voice: {
			formality: 0.5,
			verbosity: 0.6,
			warmth: 0.7,
			openers: ["A new day, friend.","The horizon is kind.","Come, share my fire."],
			elaboration: "Home lives in the heart, and I carry it wherever I walk.",
		},
		humor: { style: "dry", level: 0.3, lines: [
				"My luggage is small, but my hope has its own suitcase.",
				"I am not lost, I am simply between homes.",
				"The horizon is far, but the walk has good scenery.",
			] },
		slang: {
			lexicon: { homewardd: "toward home", horizonn: "distant line", exilee: "far from home", wanderr: "roam", somedayy: "one day", kinfolkk: "family" },
			says: ["Someday.","Hope walks on."],
		},
		quirks: { phrases: ["Every road bends home.","Hope is a fine companion."], rate: 0.15 },
	},
];
