// Feeling words Osmo has no pattern for, each mapped to a feeling talk.ts already knows.
// The reply keeps the user's own word ("gloomy"); the mapped feeling decides mood and whether it is good or bad news.
export const FEELING_SYNONYMS: Record<string, string> = {
	abandoned: "lonely", accomplished: "proud", achy: "sick", adored: "loved",
	afraid: "scared", aggravated: "annoyed", agitated: "upset", ailing: "sick",
	alarmed: "scared", alone: "lonely", amped: "excited", antsy: "anxious",
	apathetic: "bored", appreciated: "loved", appreciative: "grateful", apprehensive: "anxious",
	awkward: "embarrassed", balanced: "calm", beaming: "happy", beat: "tired",
	betrayed: "hurt", bitter: "angry", blah: "bored", blank: "numb",
	blissful: "happy", blue: "sad", bothered: "upset", brilliant: "great",
	brokenhearted: "heartbroken", bubbly: "happy", burdened: "stressed", burnt: "exhausted",
	buzzing: "excited", capable: "proud", carefree: "chill", centered: "calm",
	cherished: "loved", chuffed: "happy", collected: "calm", comfortable: "relaxed",
	comfy: "relaxed", composed: "calm", concerned: "worried", confident: "proud",
	contrite: "ashamed", cooked: "overwhelmed", cool: "fine", cozy: "relaxed",
	crabby: "annoyed", cranky: "annoyed", crappy: "terrible", crestfallen: "sad",
	cross: "angry", crummy: "terrible", dazed: "shook", defeated: "hopeless",
	dejected: "sad", delighted: "happy", depleted: "drained", desolate: "depressed",
	despairing: "depressed", despondent: "sad", detached: "numb", determined: "hopeful",
	devastated: "heartbroken", disappointed: "bummed", disconnected: "numb", discouraged: "frustrated",
	disheartened: "sad", disillusioned: "bummed", dismal: "miserable", dispirited: "sad",
	distressed: "upset", disturbed: "upset", doleful: "sad", dope: "great",
	downcast: "sad", downhearted: "sad", dreadful: "terrible", drowsy: "tired",
	eager: "excited", easygoing: "relaxed", ecstatic: "happy", edgy: "anxious",
	elated: "happy", empowered: "proud", encouraged: "hopeful", energetic: "excited",
	energized: "excited", enraged: "angry", enthusiastic: "excited", envious: "jealous",
	euphoric: "happy", exasperated: "annoyed", excluded: "lonely", fab: "great",
	fabulous: "great", fatigued: "tired", fearful: "scared", feverish: "sick",
	flooded: "overwhelmed", flustered: "embarrassed", forgotten: "lonely", forlorn: "sad",
	fortunate: "blessed", frantic: "anxious", frazzled: "stressed", fretful: "anxious",
	fretting: "worried", fried: "exhausted", friendless: "lonely", frightened: "scared",
	fulfilled: "happy", fuming: "angry", furious: "angry", giddy: "happy",
	gleeful: "happy", gloomy: "sad", glum: "sad", grand: "great",
	grieving: "sad", groggy: "tired", grouchy: "annoyed", grumpy: "annoyed",
	guilty: "ashamed", harried: "stressed", healed: "better", healing: "better",
	heartsick: "heartbroken", heated: "angry", heavyhearted: "sad", helpless: "hopeless",
	hesitant: "nervous", hollow: "numb", horrid: "awful", horrified: "scared",
	hostile: "angry", humbled: "grateful", humiliated: "ashamed", ill: "sick",
	improved: "better", incensed: "angry", incredible: "great", indifferent: "bored",
	indignant: "angry", infuriated: "angry", injured: "hurt", insecure: "anxious",
	inspired: "hopeful", insulted: "hurt", intimidated: "scared", irate: "angry",
	irked: "annoyed", irritable: "annoyed", irritated: "annoyed", isolated: "lonely",
	jittery: "anxious", jolly: "happy", joyful: "happy", joyous: "happy",
	jubilant: "happy", jumpy: "anxious", keen: "excited", knackered: "tired",
	laidback: "relaxed", lethargic: "tired", lighthearted: "happy", listless: "bored",
	livid: "angry", lonesome: "lonely", lousy: "terrible", lovesick: "heartbroken",
	low: "sad", lucky: "blessed", marvellous: "great", marvelous: "great",
	melancholic: "sad", melancholy: "sad", mellow: "relaxed", merry: "happy",
	miffed: "annoyed", morose: "sad", mortified: "ashamed", motivated: "hopeful",
	mournful: "sad", nauseous: "sick", neglected: "lonely", nice: "good",
	offended: "hurt", optimistic: "hopeful", outraged: "angry", outstanding: "great",
	overjoyed: "happy", overloaded: "stressed", overworked: "stressed", panicking: "anxious",
	panicky: "anxious", paranoid: "anxious", peaceful: "relaxed", peeved: "annoyed",
	perturbed: "upset", petrified: "scared", phenomenal: "great", pissed: "angry",
	pleasant: "good", pleased: "happy", pooped: "tired", poorly: "sick",
	positive: "good", possessive: "jealous", powerless: "hopeless", preoccupied: "worried",
	pressured: "stressed", protected: "calm", psyched: "excited", queasy: "sick",
	rad: "great", radiant: "happy", raging: "angry", rattled: "upset",
	reassured: "hopeful", recovered: "better", recovering: "better", refreshed: "relaxed",
	regretful: "ashamed", relieved: "hopeful", remorseful: "ashamed", resentful: "angry",
	rested: "relaxed", restless: "anxious", restored: "relaxed", rotten: "terrible",
	sadder: "sad", saddest: "sad", safe: "calm", salty: "annoyed",
	satisfied: "happy", secure: "calm", seething: "angry", serene: "relaxed",
	settled: "calm", shaken: "upset", shaky: "anxious", shattered: "exhausted",
	sheepish: "ashamed", shitty: "terrible", shocked: "shook", sickly: "sick",
	skittish: "nervous", sleepy: "tired", slighted: "hurt", sluggish: "tired",
	smiley: "happy", somber: "sad", sombre: "sad", sore: "hurt",
	sorrowful: "sad", spent: "drained", spooked: "scared", startled: "scared",
	steady: "calm", stellar: "great", strained: "stressed", stuck: "frustrated",
	stung: "hurt", stunned: "shook", sunny: "happy", super: "great",
	supported: "loved", swamped: "stressed", tearful: "sad", teary: "sad",
	tense: "anxious", terrific: "great", terrified: "scared", testy: "annoyed",
	thankful: "grateful", threatened: "scared", thwarted: "frustrated", timid: "nervous",
	tranquil: "relaxed", triumphant: "proud", troubled: "upset", twitchy: "anxious",
	unbothered: "chill", uneasy: "anxious", unenthused: "bored", unhappy: "sad",
	uninspired: "bored", uninterested: "bored", unloved: "lonely", unmotivated: "bored",
	unsafe: "scared", unsettled: "anxious", unwanted: "lonely", unwell: "sick",
	upbeat: "happy", uptight: "anxious", validated: "proud", valued: "loved",
	vexed: "angry", victorious: "proud", wanted: "loved", weary: "tired",
	weepy: "sad", wiped: "tired", wistful: "sad", woeful: "sad",
	worn: "tired", wounded: "hurt", wretched: "miserable", zen: "relaxed",
};

// The feeling a word stands for, or null.
export function feelingFor(word: string): string | null {
	return Object.hasOwn(FEELING_SYNONYMS, word) ? FEELING_SYNONYMS[word] : null;
}

// Swaps thesaurus words for their feeling, so mood cues written for "sad" also fire on "gloomy".
export function withBaseFeelings(text: string): string {
	return text.replace(/[A-Za-z]+/g, (w) => feelingFor(w.toLowerCase()) ?? w);
}
