// Modern slang, in two lists with different rules.

// Pure slang: tokens with no ordinary-English meaning. normalize() rewrites these to their meaning, like SLANG.
export const PURE_SLANG: Record<string, string> = {
	adorbs: "adorable", adulting: "doing grown up tasks", af: "very",
	afaik: "as far as i know", aight: "okay", asf: "very",
	aurafarming: "acting cool on purpose", ayo: "hey", ayy: "hey",
	bae: "sweetheart", bangin: "really good", bbl: "be back later",
	bbs: "be back soon", bestie: "best friend", bf: "boyfriend",
	bff: "best friend", bffl: "best friends for life", bffr: "be for real",
	bffs: "best friends", bfn: "bye for now", bops: "good songs",
	bougie: "fancy", boujee: "fancy", brokie: "someone with no money",
	bromance: "a close male friendship", brt: "be right there", capping: "lying",
	chonk: "a chubby animal", chonky: "chubby", clapback: "a sharp comeback",
	convo: "conversation", copium: "denial", crashout: "losing your temper",
	cringey: "embarrassing", deadass: "seriously", ded: "dead",
	deets: "details", dms: "direct messages", doggo: "dog",
	ez: "easy", fav: "favorite", fave: "favorite",
	finna: "going to", fml: "my life is hard", fomo: "fear of missing out",
	frfr: "for real", fs: "for sure", ftw: "for the win",
	fwiw: "for what it is worth", fyp: "for you page", gatekeep: "keep something to yourself",
	gatekeeping: "keeping something to yourself", gf: "girlfriend", ggs: "good games",
	girlboss: "an ambitious woman", girlie: "a girl", glhf: "good luck have fun",
	glowup: "a big improvement", gng: "friends", goated: "the best",
	gorg: "gorgeous", grwm: "get ready with me", gtfo: "get out",
	gyat: "wow", hangry: "hungry and angry", hbd: "happy birthday",
	hby: "how about you", heckin: "very", hella: "very",
	highk: "really", hilar: "hilarious", hmu: "hit me up",
	hopium: "false hope", icl: "i cannot lie", idc: "i do not care",
	idek: "i do not even know", idts: "i do not think so", ight: "okay",
	iirc: "if i remember correctly", iktr: "i know that is right",
	ilu: "i love you", imho: "in my honest opinion", imu: "i miss you",
	imy: "i miss you", innit: "is it not", istfg: "i swear to god",
	istg: "i swear to god", iykyk: "if you know you know", jit: "a young person",
	jomo: "joy of missing out", lmk: "let me know", looksmaxxing: "improving your looks",
	lowk: "kind of", mandem: "friends", mewing: "a jaw posture trend",
	mfw: "my face when", mkay: "okay", mog: "outshine",
	mogging: "outshining someone", moots: "mutual followers", nbd: "no big deal",
	newb: "beginner", ngmi: "not going to make it", nocap: "no lie",
	noice: "nice", noob: "beginner", npc: "a boring person",
	nvmd: "never mind", obv: "obviously", omfg: "oh my god",
	oml: "oh my lord", ong: "on god", oomf: "one of my followers",
	ootd: "outfit of the day", opp: "an enemy", opps: "enemies",
	otw: "on the way", perf: "perfect", pfp: "profile picture",
	pmo: "that makes me mad", pog: "awesome", pookie: "sweetheart",
	pov: "point of view", presh: "precious", pupper: "puppy",
	pwned: "beaten badly", ratioed: "outnumbered in replies", ridic: "ridiculous",
	rizzed: "charmed", rizzing: "charming", rizzler: "a charming person",
	rizzless: "without charm", sadge: "sad", sesh: "session",
	shawty: "a girl", sheesh: "wow", shooketh: "shocked",
	simp: "someone too eager to please", situationship: "an undefined relationship", skibidi: "silly",
	skrrt: "leaving fast", sksksk: "laughing", smdh: "shaking my head",
	smol: "small and cute", smth: "something", stanning: "being a big fan",
	sth: "something", sussy: "suspicious", tbch: "to be completely honest",
	tbt: "throwback", tf: "the heck", tfw: "that feeling when",
	tmi: "too much information", totes: "totally", tryhard: "someone trying too hard",
	tryna: "trying to", ttfn: "bye for now", ttly: "totally",
	ttys: "talk to you soon", tuff: "cool", uwu: "cute",
	vibey: "atmospheric", wagmi: "we will all make it", wagwan: "what is up",
	wbk: "we been knew", wdym: "what do you mean", whatev: "whatever",
	wth: "what the heck", wtv: "whatever", wya: "where are you at",
	yaas: "yes", yapper: "someone who talks too much", yas: "yes",
	yass: "yes", yeet: "throw hard", yessir: "yes",
	yk: "you know", ykw: "you know what", ykwim: "you know what i mean",
	yolo: "you only live once", yw: "you are welcome", zoomer: "a young person",
};

// Slang that is also an ordinary word ("I ate pizza"). Never rewritten; only used to answer "what does mid mean".
export const WORD_SLANG: Record<string, string> = {
	ate: "did amazing", aura: "coolness", bait: "obvious",
	banger: "a great song", bare: "lots of", based: "true to yourself",
	basic: "unoriginal", bet: "okay", bop: "a good song",
	bro: "a close friend", buff: "strengthen", buggin: "acting crazy",
	cap: "a lie", clout: "fame or influence", clutch: "perfectly timed",
	cooked: "doomed or done for", cringe: "embarrassing", crying: "laughing hard",
	dead: "laughing hard", drip: "stylish clothes", dub: "a win",
	era: "a phase", extra: "over the top", fax: "facts",
	fire: "really good", flex: "show off", gaslight: "make someone doubt reality",
	gassed: "excited", ghosted: "suddenly ignored", ghosting: "suddenly ignoring someone",
	glazing: "overpraising someone", goat: "the greatest of all time", ick: "a sudden turn off",
	legit: "real or genuine", lit: "exciting or fun", long: "tedious",
	mid: "mediocre or average", mood: "relatable", mother: "an icon",
	nerf: "weaken", op: "overpowered", peak: "the best",
	pressed: "upset", prob: "problem or probably", purr: "agreed",
	ratio: "more replies than likes", receipts: "proof", rent: "living in your head",
	salty: "bitter or annoyed", savage: "brutally honest", screaming: "laughing hard",
	shook: "shocked", sigma: "a lone wolf", sis: "a close friend",
	slaps: "is really good", slay: "did great", snatched: "looking great",
	spill: "share the gossip", stan: "be a huge fan of", sweaty: "trying too hard",
	tea: "gossip", trash: "really bad", tweaking: "acting crazy",
	unhinged: "wild", valid: "fair or acceptable", vibe: "a feeling or atmosphere",
	vibes: "the feeling of a place", yap: "talk too much", yapping: "talking too much",
	zesty: "flamboyant",
};

// Pure-slang keys that the subtitle word list happens to contain. Safe to rewrite anyway.
export const PURE_SLANG_IN_WORD_LIST = new Set([
	"af", "aight", "bae", "bangin", "bbs", "bestie", "bf", "bff", "bffs", "bromance", "deets", "ez", "fave", "fs", "girlie", "hella", "ight", "innit", "noob", "ong", "pookie", "sesh", "sheesh", "tmi", "totes", "tuff", "yas", "yessir", "yolo",
]);
